### ISSUE TITLE
Ignore missing asset errors on select files for use with requirejs-rails

### ISSUE THREAD

**Issue by wuservices** [rails/sprockets-rails#156]
I'm starting to use https://github.com/jwhitley/requirejs-rails for some files in my project, but I still use the asset pipeline for some JS (non-AMD) and also CSS and other things.

Because `requirejs-rails` uses `javascript_path` which eventually calls [asset_path](https://github.com/rails/sprockets-rails/blob/2de6c409267b25ecc10f1a89adb268f7afbda992/lib/sprockets/rails/helper.rb#L78-L86), I get errors from sprokets about missing assets even though it doesn't matter and the docs for `requirejs-rails` say that nothing should be in the precompile list when used with that gem.

This case is specific to using `requirejs-rails` which pretty much assumes you disable the asset pipeline completely, but is there a way for me to avoid disabling `config.assets.raise_runtime_errors` while excluding select assets from the error checking?

**Comment by baburdick** [comment]
@josh: (pardon the necro-posting) FYI: It is possible to have an asset used in development and staging that would be a security risk in production (e.g. a dev toolbar that implements quick manual testing workflows). I'm looking for a solution to exactly that puzzle now.

**Comment by schneems** [comment]
@josh doesn't monitor this repo anymore. 

One possibility is in Sprockets 4 (master) there is the ability to use env vars in a `.erb` file. If the ENV var changes then it will cause a re-compile, you could do something like this


```
# app/assets/javascripts/secure.js.erb

<% if ['development', 'staging'].include? ENV['RAILS_ENV']  %>
  // Secure code only shows up on development and staging
<% else %>
  // Nothing is here
<% end %>
```

You would still generate the file in production, but it would be empty. 

That's one way, there might be others.
