### ISSUE TITLE
Bundler could not find compatible versions for gem "sprockets-rails", rails 4.2 master

### ISSUE THREAD

**Issue by Fudoshiki** [rails/sprockets-rails#159]
Bundler could not find compatible versions for gem "sprockets-rails":
In Gemfile:
sass-rails (>= 0) ruby depends on
sprockets-rails (~> 2.0) ruby

rails (>= 0) ruby depends on
  sprockets-rails (3.0.0.beta1)
Need new gemspec for sprockets >= 2.8

need fix for commit https://github.com/rails/sprockets-rails/commit/40cd1d4c1966e8920242a8786f834e425ecacbbb

**Comment by mike-stewart** [comment]
I've got the same problem upgrading from Rails 3.2.22 to 4.0.13, and upgrading to sass-rails 5.0.0 didn't work for me. Are there any other workarounds?

**Comment by bparanj** [comment]
@sergey-alekseev : Your suggestion worked. 👍 . Thanks.
