### ISSUE TITLE
"Warning. Error encountered while saving cache..." on Sass file change

### ISSUE THREAD

**Issue by jakemauer** [rails/sprockets-rails#182]
Hi there!

I'm using the Rails 4.2 beta so apolgies if this is premature, but everytime I make a change to a sass file and reload the page, my console is filled with messages like this:

``` shell
Warning. Error encountered while saving cache b6ab29b2e6a08b27f8f3d063ccca61de1fd7e704/_global.scssc: can't dump anonymous class #<Class:0x007fe882920730>
```

The page will still load but it adds a considerable amount of time to the request. Superficially it looks like it's related to this: https://github.com/sstephenson/sprockets/pull/536 and https://github.com/sass/sass/issues/1028

More of my Gem deets:

Rails 4.2 from Github Master

``` Ruby
gem 'rails', github: 'rails/rails'
gem 'sprockets-rails', :require => 'sprockets/railtie'
gem 'sass-rails', '~> 5.0.0.beta1'
gem 'sass', '~> 3.3.0'
gem 'uglifier', '>= 1.3.0'
gem 'compass-rails', '~> 2.0.1'
gem 'bourbon', '3.2.3'
gem 'foundation-rails', '5.4.5.0'
```

Because of annoying gem interdepencies we can't switch to Sass 3.4 until they fix problems with Foundation, and we can't switch back to Sass 3.2.x because of compass-rails 2.0.x. 

I'll be happy to provide any more info. Thank you!

**Comment by mocoso** [comment]
You can see this issue has been fixed in the sass-rails project, see https://github.com/rails/sass-rails/pull/292
