### ISSUE TITLE
Replace precompile list with manifest files

### ISSUE THREAD

**Issue by josh** [rails/sprockets-rails#191]
`sprockets-rails` 3.x can depend on a new feature in `sprockets` 3.x, asset links.

The default `config.assets.precompile` list can pretty be replaced with a `manifest.js` file convention.

``` js
// app/assets/manifest.js
//= link application.js
//= link application.css
//= link_tree ./fonts
//= link_tree ./images
```

**Comment by Fudoshiki** [comment]
https://github.com/ai/autoprefixer-rails/issues/52

**Comment by josh** [comment]
I'm pretty sure @lucasmazza has seen this issue, but just mentioning him here. He has already done some awesome work to move this along. Thanks again @lucasmazza!

**Comment by lucasmazza** [comment]
@josh thanks! let me know if there's anything else in this front that I can help with.

**Comment by josh** [comment]
We still got some time, but this is probably going to be a blocker for getting sprockets 4.x switched over to master.

https://github.com/rails/sprockets/pull/1
