### ISSUE TITLE
Could not find gem 'sprockets-rails (~> 2.0) ruby', which is required by gem 'rails (= 4.1.0) ruby', in any of the sources.

### ISSUE THREAD

**Issue by vtrkanna** [rails/sprockets-rails#211]
Hi

I'm facing some small issue 

Could not find gem 'sprockets-rails (~> 2.0) ruby', which is required by gem 'rails (= 4.1.0) ruby', in any of the sources.

Thanks.

**Comment by rafaelfranca** [comment]
Thank you for reporting. This is a dependency resolving problem and it is not related to this gem. Make sure you configured the right set of dependencies in your Gemfile
