### ISSUE TITLE
Compiling js for distribution

### ISSUE THREAD

**Issue by guyisra** [rails/sprockets-rails#212]
Is there a way to use sprockets to uglify/minify a standalone js file meant for distribution as a third party (plug ins, extensions, etc)?

My use case - build a standalone js, but keep it part of the rails app and project (repo, versioning, etc) so everytime I deploy that standalone js will be recompile due to bug fixes, dependcies, gem and/or other js plugins change

The problem is that using sprockets, I can't set a filename without a digest, so I can't distribute it as the filename will keep changing. If I exclude it from sprockets, it won't compile.. 

What can be done?

**Comment by rafaelfranca** [comment]
You could just copy the digested file without digest in your deploy tasks.
