### ISSUE TITLE
Precompile Assets failed with default configurations

### ISSUE THREAD

**Issue by sn3ek** [rails/sprockets-rails#217]
I encountered a problem with version 2.2.3. When I deploy my application in production mode the assets will not be precompiled, and an error raises that I should manually add those file to the ` Rails.application.config.assets.precompile += %w(<files>)`. Affected files are e.g.:

`*.eof *.ttf *.svg *.swf *.woff *gif`

For now our work around is to downgrade to `gem 'sprockets-rails', '2.2.2'`.

**Comment by stuartgibson** [comment]
+1

**Comment by jasonblalock** [comment]
+1

**Comment by drewbailey** [comment]
+1  temp workaround other then downgrading
```ruby
Rails.application.config.assets.precompile += [/.*\.png/,/.*\.ico/,/.*\.jpg/,/.*\.js/,/.*\.scss/]
```

**Comment by josh** [comment]
It probably is related to 3bd4470f763fba61cc6def29fe1b5c8f7e7214bb which fixed a bug including *other* app/assets directories.

Are these apps in `your/app/assets/images/*` or `some/other/directory/app/assets`?

**Comment by cristiansorinel** [comment]
I encountered this problem when loading assets from font-awesome-rails gem, version 4.2.0.0 and from jquery-ui-rails, version 5.0.3

**Comment by rmm5t** [comment]
@josh This was also reported on font-awesome-rails (asset gem).
https://github.com/bokmann/font-awesome-rails/issues/124

So, I suspect that any gem that has an `app/assets` directory and no explicit `precompile` directives is potentially affected.

**Comment by stuartgibson** [comment]
Yep. We have a large internal app with aspects split into engines and all app/assets in the individual engines are affected by this. 

—

**Comment by josh** [comment]
Reverted in aeac9fe3d0ea5740de6dcdb26ed4f2af65bf6a5c and release 2.2.4.

However, this was the intended change and 3.x will not include those paths by default. I'll make a note in the changelog.

**Comment by josh** [comment]
Sorry about that again. Was the original issue #154.

**Comment by josh** [comment]
Cross referencing #191, which will hopefully obsolete `config.assets.precompile` and provide something that is actually composable for plugins/engines to provide manifests of all there internal files.
