### ISSUE TITLE
all application.(js,css) files pulled in

### ISSUE THREAD

**Issue by scashin133** [rails/sprockets-rails#218]
I have a bower depedency on [jquery-sortable](https://github.com/johnny/jquery-sortable), which includes application.(css.sass,js) files.

The default precompile logic https://github.com/rails/sprockets-rails/blob/master/lib/sprockets/railtie.rb#L69 causes all application css and js files to be precompiled which was not the desired effect for this library.

```ruby
2.2.0 :001 > 'vendor/assets/bower_components/jquery-sortable/source/js/application.js' =~ /(?:\/|\\|\A)application\.(css|js)$/
 => 56
```

Was this intentional?

There was an issue filed with jquery-sortable https://github.com/johnny/jquery-sortable/issues/134 asking them to remove it but I didn't understand why it was precompiling it in the first place.

**Comment by josh** [comment]
I definitely agree with you and I attempted to "fix" it recently, but apparently people are depending on this sort of thing. But I'm planning to have it locked down in the next major release 3.x which can have backwards incompatible changes. Thanks!

**Comment by scashin133** [comment]
Sounds good just wanted to make sure.

On Monday, January 26, 2015, Joshua Peek <notifications@github.com> wrote:

> I definitely agree with you and I attempted to "fix" it recently, but
> apparently people are depending on this sort of thing. But I'm planning to
> have it locked down in the next major release 3.x which can have backwards
> incompatible changes. Thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rails/sprockets-rails/issues/218#issuecomment-71580410>
> .
>


-- 
http://about.me/seancashin/bio

**Comment by bborn** [comment]
+1 also think I'm running into this. `bower install jquery-sortable` brings in all the development files (sass, etc.) which then don't precompile correctly. Wouldn't it be better to only include the compiled js and css files?
