### ISSUE TITLE
Rails.application.assets is nill

### ISSUE THREAD

**Issue by Fudoshiki** [rails/sprockets-rails#223]
https://github.com/ai/autoprefixer-rails/issues/52

**Comment by rafaelfranca** [comment]
Yeah. The gems need to fix it.

**Comment by Fudoshiki** [comment]
What need change in autoprefixer-rails?

**Comment by rafaelfranca** [comment]
It need to run their code in a `after_initialize` block. @josh do you remember why you choose `after_initialize` instead a normal initialize?

**Comment by Fudoshiki** [comment]
sharevari@MG392:~/repository/project/torii$ rake assets:precompile RAILS_ENV=production
I, [2015-02-05T00:51:20.237542 #31597]  INFO -- : Writing /home/sharevari/repository/project/torii/public/assets/application-f2ff325ecebb98654e9789f52c1d0805b165391a6126883844f39d17c78bfb32.js
I, [2015-02-05T00:51:20.241728 #31597]  INFO -- : Writing /home/sharevari/repository/Sekai Bujyutsu Renmei/torii/public/assets/application-e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855.css
rake aborted!a
NoMethodError: undefined method `resolve' for nil:NilClass
/home/sharevari/repository/Sekai Bujyutsu Renmei/torii/config/initializers/assets.rb:13:in `block in <top (required)>'
/home/sharevari/.rvm/gems/ruby-2.2-head/bundler/gems/sprockets-a2e030f03603/lib/sprockets/manifest.rb:123:in `call'
/home/sharevari/.rvm/gems/ruby-2.2-head/bundler/gems/sprockets-a2e030f03603/lib/sprockets/manifest.rb:123:in `block (2 levels) in find'
/home/sharevari/.rvm/gems/ruby-2.2-head/bundler/gems/sprockets-a2e030f03603/lib/sprockets/manifest.rb:123:in `any?'
/home/sharevari/.rvm/gems/ruby-2.2-head/bundler/gems/sprockets-a2e030f03603/lib/sprockets/manifest.rb:123:in `block in find'
/home/sharevari/.rvm/gems/ruby-2.2-head/bundler/gems/sprockets-a2e030f03603/lib/sprockets/legacy.rb:113:in `block (2 levels) in logical_paths'
/home/sharevari/.rvm/gems/ruby-2.2-head/bundler/gems/sprockets-a2e030f03603/lib/sprockets/path_utils.rb:208:in `block in stat_tree'
/home/sharevari/.rvm/gems/ruby-2.2-head/bundler/gems/sprockets-a2e030f03603/lib/sprockets/path_utils.rb:192:in `block in stat_directory'
/home/sharevari/.rvm/gems/ruby-2.2-head/bundler/gems/sprockets-a2e030f03603/lib/sprockets/path_utils.rb:189:in `each'
/home/sharevari/.rvm/gems/ruby-2.2-head/bundler/gems/sprockets-a2e030f03603/lib/sprockets/path_utils.rb:189:in `stat_directory'
/home/sharevari/.rvm/gems/ruby-2.2-head/bundler/gems/sprockets-a2e030f03603/lib/sprockets/path_utils.rb:207:in `stat_tree'
/home/sharevari/.rvm/gems/ruby-2.2-head/bundler/gems/sprockets-a2e030f03603/lib/sprockets/legacy.rb:104:in `each'
/home/sharevari/.rvm/gems/ruby-2.2-head/bundler/gems/sprockets-a2e030f03603/lib/sprockets/legacy.rb:104:in `block in logical_paths'
/home/sharevari/.rvm/gems/ruby-2.2-head/bundler/gems/sprockets-a2e030f03603/lib/sprockets/legacy.rb:103:in `each'
/home/sharevari/.rvm/gems/ruby-2.2-head/bundler/gems/sprockets-a2e030f03603/lib/sprockets/legacy.rb:103:in `logical_paths'
/home/sharevari/.rvm/gems/ruby-2.2-head/bundler/gems/sprockets-a2e030f03603/lib/sprockets/manifest.rb:122:in `find'
/home/sharevari/.rvm/gems/ruby-2.2-head/bundler/gems/sprockets-a2e030f03603/lib/sprockets/manifest.rb:147:in `compile'
/home/sharevari/.rvm/gems/ruby-2.2-head/bundler/gems/sprockets-rails-6f787e56c6be/lib/sprockets/rails/task.rb:68:in `block (3 levels) in define'
/home/sharevari/.rvm/gems/ruby-2.2-head/bundler/gems/sprockets-a2e030f03603/lib/rake/sprocketstask.rb:147:in `with_logger'
/home/sharevari/.rvm/gems/ruby-2.2-head/bundler/gems/sprockets-rails-6f787e56c6be/lib/sprockets/rails/task.rb:67:in `block (2 levels) in define'
Tasks: TOP => assets:precompile


assets.rb
'''
# Be sure to restart your server when you modify this file.

# Version of your assets, change this if you want to expire all your assets.
Rails.application.config.assets.version = '1.0'

# Add additional assets to the asset load path
# Rails.application.config.assets.paths << Emoji.images_path

# Precompile additional assets.
# application.js, application.css, and all non-JS/CSS in app/assets folder are already added.
Rails.application.config.assets.precompile << proc do |path|
  if path =~ /\.(css|js)\z/
    full_path = Rails.application.assets.resolve(path).to_s
    app_assets_path = Rails.root.join('app', 'assets').to_s
    vendor_assets_path = Rails.root.join('vendor', 'assets').to_s
    if (full_path.starts_with? app_assets_path) || (full_path.starts_with? vendor_assets_path)
      puts "including asset: #{ full_path }"
      true
    else
      puts "excluding asset: #{ full_path }"
      false
    end
  else
    false
  end
end
'''

**Comment by Fudoshiki** [comment]
only on master branch
v2.2.4  working

**Comment by josh** [comment]
I'll probably have them switch over to using `config.assets.configure do |env|`. I'll open a autoprefixer PR.

btw, all these changes only affect people using rails/master and sprockets-rails/master. Both of which won't be released as stables for months.

**Comment by Fudoshiki** [comment]
thank you
