### ISSUE TITLE
What is initializer "sprockets.environment"?

### ISSUE THREAD

**Issue by rmosolgo** [rails/sprockets-rails#227]
Hi there, 

I'm trying to track down [an issue](https://github.com/reactjs/react-rails/issues/148) that may be related to our chaining initializers like this:

```ruby
initializer "react_rails.setup_vendor", :after => "sprockets.environment" do |app|
  # ...
end
```

I'm hoping to find more about the `sprockets.environent` initializer, but I couldn't find it in this repo. I read through `railtie.rb` and tried searching the rest of the repo. 

Could you help me find some info about it? I also see it mentioned in this [SO](http://stackoverflow.com/a/21869189/1741654)

Thanks!

**Comment by rafaelfranca** [comment]
This initializer only existed in the version 1.x of this plugin. Here is the code https://github.com/rails/sprockets-rails/blob/v1.0.1/lib/sprockets/rails/railtie.rb#L18.

**Comment by rmosolgo** [comment]
Thanks!
