### ISSUE TITLE
Issues having a file that matches manifest-*.json in your assets directory

### ISSUE THREAD

**Issue by juddblair** [rails/sprockets-rails#229]
So, we had a JSON manifest we were using for our favicons following this W3C draft - https://w3c.github.io/manifest/ . The file was named `manifest.json`, and was living alongside the icon assets in assets/images.

What ends up happening is this file gets precompiled by the asset pipeline, and you now have:
`manifest-<some hash>.json`
`manifest-<some other hash>.json`
in your resulting public/assets directory

As best I can tell, when you start the app, whatever `.first` returns from all files that match `manifest-*.json` is used as the asset pipeline manifest, which ends up causing asset helpers to return paths to uncompiled assets when the wrong manifest is selected. The matcher is extra confusing because even if you renamed that file, say `manifest-favicons.json`, it would still match and exhibit the same behavior.

Seems like precompilation should fail when this situation is detected. 

(and yeah, we're doing it wrong since static assets should live in /public, but this still seems like a pretty dangerous gotcha)

**Comment by josh** [comment]
Yeah, I'd really like to rename that file.

First it should probably be a `.something.json`. I think that will also fit into many default configs to prevent it from being served. Then maybe naming it something like `.sprockets-mainfest.json` would go even further.

wdyt?

**Comment by rafaelfranca** [comment]
:+1: for `.sprockets-manifest.json`

**Comment by josh** [comment]
The trick is probably going to be transitioning away from the old name. There definitely has to be a good upgrade path here.

This 3.x beta seems like a good time. We can probably support both styles on 3.x and only this new one on 4.x.

**Comment by juddblair** [comment]
Yup, I think that's a good approach, and won't clash with any assets you actually want served. :+1: here as well.

**Comment by josh** [comment]
Cool.

I'll probably take a look at this sometime over this weekend. Otherwise, if someone wants to get a PR started sooner, I'm happy to help up and give direction.

**Comment by josh** [comment]
Ah, I just realized this is on the sprockets-rails issue tracker. The change should be made to sprockets core. I'll open a cross referencing issue over there.

**Comment by rafaelfranca** [comment]
This is fixed at sprockets 3.

**Comment by Rezaul08** [comment]
I am new Email account finishes
