### ISSUE TITLE
Create stub with regular expression

### ISSUE THREAD

**Issue by jonricaurte** [rails/sprockets-rails#230]
I have an angular front end and I want to include all my unit test files in my project assets(in each feature module). Currently I have to stub every test file that is included, but what would be more ideal is if I could pass in a regular expression and have stub remove all test files that end in _spec.coffee.

Thanks!

**Comment by josh** [comment]
You can use erb to call stub.

``` erb
<%= stub_asset some_filename %>
```

But be warn'd you'll have to do deal with all the subdirectory dependency tracking yourself.

**Comment by jonricaurte** [comment]
Closing this ticket in favor of:

https://github.com/rails/sprockets/issues/13
