### ISSUE TITLE
Assets are precompiled twice in development

### ISSUE THREAD

**Issue by rusikf** [rails/sprockets-rails#233]
1) gem install rails ( 4.2.1)

2) Create new project( skip 2 step, if use [my repo](https://github.com/rusikf/my_project) for reproducing this issue)
2.1)``` rails new myproject```
2.2) ```rails g controller welcome```
2.3) Create index action in welcome controller and view for it
2.4) Add welcome controller to routes (root for example)
2.5) create ```app/assets/javascripts/vendor.js```
2.6) Remove require_tree from application.js and add `//= require vendor`
2.7) In vendor.js write alert('i am a vendor);
2) run ```bin/rails s```
Everything is fine!

3) Stop rails s
3.1) rm -rf public/assets
3.2) ```rake assets:precompile```
3.3) ```rails s```
3.4) Alert showing twice!!! ( it is in application.js inner and in vendor.js source in html) Why?

4) If repeat step 3 with ```config.assets.debug = true```, alert showing once.

**Comment by rafaelfranca** [comment]
This is how assets debug works. If you enable it, sprockets will add each one of your dependencies in the HTML. This is why you should not run `rake assets:precompile` in development.
