### ISSUE TITLE
Is requiring css outside app/css directory forbidden in 3.x

### ISSUE THREAD

**Issue by TheR2** [rails/sprockets-rails#236]
I have this require directive in one of my application.css file. 
 *= require ../javascripts/drg_default_html_editor/elfinder/css/elfinder.min.css
 *= require ../javascripts/drg_default_html_editor/elfinder/css/theme.css

and with last version I get error in development (didn't yet tried production):
couldn't find file '../javascripts/drg_default_html_editor/elfinder/css/elfinder.min.css' with type 'text/css'

I could copy files to css local directory but the idea is not to do too much handwork after installing another version of script library.

Or is there another solution?

by
TheR

**Comment by josh** [comment]
Can you just do `require drg_default_html_editor/elfinder/css/elfinder.min.css`?

**Comment by josh** [comment]
I did try to improve the error message in this case https://github.com/rails/sprockets/commit/0c24a1c9d550ad9b2b44a35e35dbcf9fcf210ee1

**Comment by TheR2** [comment]
Yep it works now. At least in development. 

I was struggling a lot with sprockets at the beginning and this was probably not one of the finest solutions that worked ;-(

Thanks. I am closing the issue.

by
TheR
