### ISSUE TITLE
gemspec still says it is version 2.3.0

### ISSUE THREAD

**Issue by mrueg** [rails/sprockets-rails#256]
https://github.com/rails/sprockets-rails/blob/2.x/sprockets-rails.gemspec

Should be 2.3.1 :)

**Comment by rafaelfranca** [comment]
Thank you for the issue but we only bump the version when we release.

**Comment by rafaelfranca** [comment]
hmm, you are right. I think @josh forgot to push the change.

**Comment by rafaelfranca** [comment]
It should be fixed now.
