### ISSUE TITLE
What does LOOSE_ASSETS do?

### ISSUE THREAD

**Issue by radar** [rails/sprockets-rails#263]
I'm documenting the initialization process for Rails for my book ["Deep Dive Rails"](http://leanpub.com/ddr) and I'm stumped as to what the `LOOSE_ASSETS` constant defined in `Sprockets::Railtie` does.

Can someone offer an explanation for this?

**Comment by rafaelfranca** [comment]
It defines a lambda that includes all the non-css and non-js files from `app/assets` folder on the precompile list. Things like images, fonts, txt files, etc.

I hope this help. Let me know if you need more information about it.

**Comment by radar** [comment]
Thank you, that helps a lot :)
