### ISSUE TITLE
How use sprockets 4 and manifest.js

### ISSUE THREAD

**Issue by Fudoshiki** [rails/sprockets-rails#266]
I have manifest.js in app/assets
```
// manifest.js
//
// JS bundles
//= link ./javascripts/application.js
//
// CSS bundles
//= link_tree ./stylesheets
//
// Pull in all app/assets/images/ since app/views may link to them
//= link_tree ./images
```
 but rails don't see this

Asset was not declared to be precompiled in production.
Add `Rails.application.config.assets.precompile += %w( application.js )` to `config/initializers/assets.rb` and restart your server

How declare Rails.application.config.assets.precompile, this dont working with lambda and regex in new version

assets.rb
```
# Be sure to restart your server when you modify this file.

# Version of your assets, change this if you want to expire all your assets.
Rails.application.config.assets.version = '1.0'

# Add additional assets to the asset load path
# Rails.application.config.assets.paths << Emoji.images_path

# Precompile additional assets.
# application.js, application.css, and all non-JS/CSS in app/assets folder are already added.
Rails.application.config.assets.precompile = %w( manifest.js )
```
rails 4.2
sprockets 4
sprockets-rails 5.0.3

**Comment by prathamesh-sonpatki** [comment]
@Fudoshiki Which version of Rails are you using?

**Comment by Fudoshiki** [comment]
with sprockets 3
```
# Be sure to restart your server when you modify this file.

# Version of your assets, change this if you want to expire all your assets.
Rails.application.config.assets.version = '1.0'

# Add additional assets to the asset load path
# Rails.application.config.assets.paths << Emoji.images_path

# Precompile additional assets.
# application.js, application.css, and all non-JS/CSS in app/assets folder are already added.
Rails.application.config.assets.precompile << proc do |path|
  if path =~ /\.(css|js)\z/
    full_path = Rails.application.assets.resolve(path).to_s
    app_assets_path = Rails.root.join('app', 'assets').to_s
    vendor_assets_path = Rails.root.join('vendor', 'assets').to_s
    if (full_path.starts_with? app_assets_path) || (full_path.starts_with? vendor_assets_path)
      puts "including asset: #{ full_path }"
      true
    else
      puts "excluding asset: #{ full_path }"
      false
    end
  else
    false
  end
end
```
precompiled all assets, with sprockets 4

/.rvm/gems/ruby-2.2.2/bundler/gems/sprockets-44a829ea5def/lib/sprockets/uri_utils.rb:75:in `valid_asset_uri?': undefined method `start_with?' for #<Proc:0x000000050e40c0> (NoMethodError)

**Comment by Fudoshiki** [comment]
any best practice use new sprockets or doc?
1) How declare precompile assets now?
2) Do I need use manifest.js and where hold it
3) Do I need use application.js/css files?

**Comment by prathamesh-sonpatki** [comment]
@Fudoshiki For using `app/assets/manifest.js` in existing Rails app, I had opened PR https://github.com/rails/rails/pull/21059 on Rails side. It mimics changes done in https://github.com/rails/sprockets-rails/pull/232 for Rails 4.2.x apps.

**Comment by Fudoshiki** [comment]
Nice

**Comment by prathamesh-sonpatki** [comment]
Also you can see an example of upgrading existing Rails app to sprockets 4 here - https://github.com/codetriage/codetriage/pull/380/files. It's still WIP. We don't have any example of passing proc to `Rails.application.config.assets.precompile` though.

**Comment by Fudoshiki** [comment]
With working manifest.js proc support in Rails.application.config.assets.precompile don't need

**Comment by Fudoshiki** [comment]
Thank you very much

**Comment by rsmything** [comment]
// manifest.js
//
// JS bundles
//= link ./javascripts/application.js
//
// CSS bundles
//= link_tree ./stylesheets
//
// Pull in all app/assets/images/ since app/views may link to them
//= link_tree ./images


Hello, if use this example, sprockets are creating wrong url(path) for css and other assets.
On the page it displayed as <script src="/javascripts/application.js" async="async" data-turbolinks-track="true"></script> without digest and with wrong path "/javascripts/application.js" instead "/assets/application-<digest>.js"

How to configure sprockets with "/assets/application-<digest>.js"?

**Comment by Fudoshiki** [comment]
links generated by javascript_include_tag / stylesheet_link_tag broken too

**Comment by prathamesh-sonpatki** [comment]
@rsmything Which version of Rails you are using? Please try with this patch https://github.com/rails/rails/pull/21059

**Comment by rsmything** [comment]
4.2

**Comment by Fudoshiki** [comment]
This is with patch
