### ISSUE TITLE
Support for styled static 500 error pages via opt-in undigested 

### ISSUE THREAD

**Issue by johannesluedke** [rails/sprockets-rails#274]
In rails I want to use a styled static 500/404 error page. The best way to do this was to use undigested assets for css, js and logo files which used to be generated in Rails 3.x. I read issue #49 and am aware of the "caching old version forever" bug, but I think for the 500 error page this is a trade-off, which the developer should decide about.

The current best solution as suggested in #49 and bibwild.wordpress.com/2014/10/02/non-digested-asset-names-in-rails-4-your-options seems to be to write a custom rake task and wire it up indiviudally with ones capistrano setup. I am not quite happy that this should be the only official solution to deal with scenario.
I think the use case to want to have styled 500 error page without manual asset duplication is quite common (which application wouldn't want to have it?). If there is a better way for styled 500 error pages without manual asset duplication I am also happy to learn about it.

I would wish for a white list option to have undigested asset files.

**Comment by rafaelfranca** [comment]
This will be fixed with https://github.com/rails/sprockets-rails/pull/239

**Comment by johannesluedke** [comment]
Cool, so it will be dealt with in #239  :+1: 

Thanks for your efforts for rails!
