### ISSUE TITLE
Support for `config.assets.cache_store` dropped??

### ISSUE THREAD

**Issue by brauliobo** [rails/sprockets-rails#283]
I have migrated an app from Rails 3 to Rails 4 and notice the cache_store just stopped working.

Just saw the commit 5f83625 and it seems the support was just dropped!! Any reason for this?

The rails guides at http://guides.rubyonrails.org/asset_pipeline.html still mentions it. :(

**Comment by prathamesh-sonpatki** [comment]
@brauliobo It still works, the API is changed - http://edgeguides.rubyonrails.org/asset_pipeline.html#assets-cache-store. Closing this issue now.
