### ISSUE TITLE
Issue with rake assets:precompile

### ISSUE THREAD

**Issue by askehansen** [rails/sprockets-rails#287]
Should sprockets try to precompile files in vendor/ that hasn't been required?
It causes issue with some bower packages.

I made a sample app that demonstrates it: https://github.com/askehansen/assets-issue
It just has a package in the vendor directory and assets:precompile fails

**Comment by rafaelfranca** [comment]
The name of the [assets inside vendor is `application.css.sass`](https://github.com/askehansen/assets-issue/blob/master/vendor/assets/javascripts/jquery-sortable/source/css/application.css.sass). Sprockets will try to precompile everything called application.css or application.js, so yeah it is expected
