### ISSUE TITLE
Changelog for 3.0 ?

### ISSUE THREAD

**Issue by bricesanchez** [rails/sprockets-rails#288]
Hello,

Where could i find the changelog for 3.0 ?

Thanks !

**Comment by jfeaver** [comment]
Hey @bricesanchez,

I came looking for one of those too! Unfortunately, I don't think there is one. There IS a page on the sprockets gem page for upgrading though: https://github.com/rails/sprockets/blob/master/UPGRADING.md

Also, GitHub issues are for problems with the software and not recommended for questions. You'll get faster responses on the Rails' [IRC or mailing list](http://rubyonrails.org/community/).

**Comment by rafaelfranca** [comment]
I still need to write it. I'll do tomorrow.

**Comment by mockdeep** [comment]
Just ran into issues upgrading. It would be good to have a guide to the changes from `sprockets-rails` 2.3 to 3.

**Comment by jasonkim** [comment]
@rafaelfranca Is this somewhere? I can't seem to find it. Thanks.

**Comment by rafaelfranca** [comment]
Yes. https://github.com/rails/sprockets-rails/releases/tag/v3.0.0

**Comment by jasonkim** [comment]
Thank you!

**Comment by bricesanchez** [comment]
Thank you!
