### ISSUE TITLE
register_engine error

### ISSUE THREAD

**Issue by tommiller1** [rails/sprockets-rails#292]
Hi,

I have the following line inside config/initializers/slim.rb:
Rails.application.assets.register_engine('.slim', Slim::Template)

This worked fine before 3.0.0 (released yesterday). Now I keep getting this error:
/slim.rb:2:in `<top (required)>': undefined method `register_engine' for nil:NilClass (NoMethodError)

Everything works if I revert to sprockets-rails 2.3.3 but I want to know how to make it work on the new version.

Thanks.

**Comment by rafaelfranca** [comment]
You need to use the configure blocks

```ruby
Rails.application.config.assets.configure do |env|
  env.register_engine('.slim', Slim::Template)
end
```

`Rails.application.assets` is `nil` when `Rails.application.config.compile` is `false`.

**Comment by tommiller1** [comment]
Excellent, thank you!
