### ISSUE TITLE
Assets expected to be precompiled?

### ISSUE THREAD

**Issue by Capncavedan** [rails/sprockets-rails#293]
Ruby 2.2.4, Rails 4.2.5, updated to sprockets-rails 3.0.0 from 2.3.3, encountered an issue where teaspoon running jasmine tests expected assets to be individually precompiled.

Tried adding `support/bind-poly.self.js` to the initializer as suggested, but then encountered same issue with the next .js file.

I’m unsure why teaspoon mentions it is running in production as the output of `p Rails.env` run in its config file is “development” 

````Starting the Teaspoon server...
Teaspoon running default suite at http://127.0.0.1:60921/teaspoon/default
Error: ActionView::Template::Error: Asset was not declared to be precompiled in production.
Add `Rails.application.config.assets.precompile += %w( support/bind-poly.self.js )` to `config/initializers/assets.rb` and restart your server
/home/travis/build/MerchantsBonding/hubble/vendor/bundle/ruby/2.2.0/gems/sprockets-rails-3.0.0/lib/sprockets/rails/helper.rb:350:in `raise_unless_precompiled_asset’
````

**Comment by rafaelfranca** [comment]
That is a teaspoon issue. I had the same problem in my application. It should be adding all the files in the precompile list since it is using `javascript_tag`. You can either disable the precompile check or ask them to properly register the assets that are being used in the precompile list.

**Comment by Capncavedan** [comment]
@rafaelfranca thanks for the info. Could you point me toward how to "disable the precompile check"?

**Comment by rafaelfranca** [comment]
Urgh,you can't disable anymore in sprockets-rails 3. So the only way is to get it fixed in teaspoon.

**Comment by Capncavedan** [comment]
OK, thanks.  I’ll open an issue in the teaspoon project.
