### ISSUE TITLE
Rails.application.assets returns nil on version 3.5.2

### ISSUE THREAD

**Issue by adisos** [rails/sprockets-rails#294]
I just updated to 3.5.2 from 2.3.3 and it returns nil.

I used that to fetch my assets:
`Rails.application.assets['application.scss'].to_s`

Is there another way to solve my problem?

**Comment by khustochka** [comment]
Reproduced for me in 3.0.0 in production env. Not reproduced in development.

**Comment by leesmith** [comment]
I'm seeing the same thing. Rails 4.2.5 and sprockets-rails 3.0.0.

**Comment by rafaelfranca** [comment]
Yes, this is one of the main changes in sprockets-rails 3. If you set `Rails.application.config.assets.compile` to `false` the `Rails.application.assets` will be `nil` to avoid you to compile assets by accident in production for example. When you call `Rails.application.assets['application.scss'].to_s` you are compiling that asset, if you do it in production (what is not recommended) you need to enable compilation.

**Comment by leesmith** [comment]
Thanks @rafaelfranca. Looks like my issue stems from wicked_pdf behaving badly.

**Comment by Pepan** [comment]
Hey. I use this inquiry to determine whether the asset exists. How do I find it now?
```Ruby
      -if Rails.application.assets.find_asset("icons/files/i#{annex.ext.downcase}.png")
        = image_tag("icons/files/i#{annex.ext.downcase}.png", size: '50x50')
      - else
        = image_tag('icons/files/i.unknown.png', size: '50x50')
```

**Comment by rafaelfranca** [comment]
`if assets_manifest["icons/files/i#{annex.ext.downcase}.png"]`

**Comment by miks** [comment]
`assets_manifest["icons/files/i#{annex.ext.downcase}.png"]` is supposed to works also in test/development environment?

**Comment by cseelus** [comment]
I guess it should be `if assets_manifest.assets["icons/files/i#{annex.ext.downcase}.png"]`

Not really a good replacement for `find_assets` imho though, as it behaves different in production and development and its documentation is scarce, to say the least.

**Comment by lfzawacki** [comment]
The fact that this is not documented and works differently in production and dev is a real downgrade from `find_assets`

**Comment by rafaelfranca** [comment]
`find_assets` is still there. You just need to understand that it **compiles** the assets in run time and you need to enable that behavior.

**Comment by khustochka** [comment]
I've been using `Rails.application.assets` in order to precompile only those assets that reside in `app/assets/` (but not those in `lib/assets` or `vendor\assets`).

````ruby
app_assets_path = Rails.root.join('app', 'assets').to_path
Rails.application.config.assets.precompile << Proc.new { |path|
  # return true to compile asset, false to skip
  if path =~ /\.png$/
    true
  elsif path =~ /\.(css|js)\z/
    full_path = Rails.application.assets.resolve(path)
    full_path.starts_with?(app_assets_path)
  else
    false
  end
}
````

Not sure what is the alternative now. Of course I can somehow generate a list of asset files, but this is complicated by subfolders and different extensions, i.e. `.js`, `.js.coffee`, `.sass`.

**Comment by rafaelfranca** [comment]
https://github.com/rails/sprockets-rails/blob/master/lib/sprockets/railtie.rb#L62

**Comment by khustochka** [comment]
@rafaelfranca Thank you!

**Comment by BenMorganIO** [comment]
Hmmm I've discovered that I've been compiling the assets when I send an email.

So, the asset compile for `mailer.css` occurs in Sidekiq. I feel like we should add a `permitted_compile` method. This way we can compile assets in a job. These would probably be assets that would never be stored in a CDN, but rather be compiled and even inlined into the HTML, such as with emails.

@rafaelfranca I was listening to your Bikeshed podcast today and discovered this issue a few hours later within a Rails app :p. I'm thinking its definitely a great idea, but we could also take advantage of this for making CSS + mailer.css work together better.

**Comment by tom-brown** [comment]
I'm on rails 5.2 and I am having this problem and finally added an application helper to find_assets in both development and production:

```
def image_exists?(path)
    if Rails.env == "development" && Rails.application.assets.find_asset(path)
      return true
    elsif Rails.env == "production" && Rails.application.assets_manifest.assets[path]
      return true
    else
      return false
    end
 end
```
then I can call image_exists?(path) from anywhere in both dev and production.  There is probably a better way to do this, but it works for now.
