### ISSUE TITLE
No way to check if asset exists in production

### ISSUE THREAD

**Issue by amw** [rails/sprockets-rails#298]
I used to have this in my layout:

```
<% page_js = "page_scripts/#{controller_name}.js" %>
<% if Rails.application.assets.find_asset(page_js).present? %>
```

Now `Rails.application.assets` is `nil` if `config.assets.compile` is `false`. I get why and I guess that's fine. I tried to look for another way to check if I have dedicated JS file for particular controller and found [ActionView#precompiled_asset_checker](https://github.com/rails/sprockets-rails/blob/master/lib/sprockets/railtie.rb#L205) which internally uses `Rails.application.asset_precompiled?`. Unfortunately these also don't seem to work when `config.assets.compile` is `false`.

```
<% if precompiled_asset_checker.call(page_js) %>
```

This raises `ActionView::Template::Error: manifest requires environment for compilation` which is a translation of `Sprockets::Error: manifest requires environment for compilation` raised [here](https://github.com/rails/sprockets/blob/master/lib/sprockets/manifest.rb#L117).

I think the names `asset_precompiled?` and `precompiled_asset_checker` suggest that these should work with precompiled assets in production without the need for compilation environment.

Is there a way to perform this kind of check without compilation environment in production? Other than loading and parsing the manifest file manually, I mean.

**Comment by benilovj** [comment]
Hi @amw, I wonder whether it's possible to use `Rails.application.assets_manifest.assets[page_js].present?` for this purpose? I'm not sure myself, perhaps this is reaching too far into the Sprockets internals...

**Comment by amw** [comment]
Yes, this does work. Thanks.

Because development environment does not have a static manifest file I have to use different checks for development and production. Something like this:

```
 def asset_available? logical_path
    if Rails.configuration.assets.compile
      Rails.application.precompiled_assets.include? logical_path
    else
      Rails.application.assets_manifest.assets[logical_path].present?
    end
  end
```

But this is good enough for me.

**Comment by DannyBen** [comment]
Thank you @amw  - I have spent quite some time looking for a solution, and it seems all the StackOverflow answers are not working in production.

Your method seems to work, so I have [placed it in SO](http://stackoverflow.com/a/35319530/413924) for the benefit of future victims.

**Comment by edenvicary** [comment]
@amw or you could:

```ruby
  def assets
    Rails.application.precompiled_assets &
      Rails.application.assets_manifest.assets
  end

  def exists?(file)
    assets.include? file
  end
```

**Comment by amw** [comment]
@edenvicary Your method doesn't work in development environment where there is no asset manifest.

**Comment by midnightmonster** [comment]
In development, @amw 's `asset_available?` method checks only _precompiled_ assets. That makes it correct according to its name but not as helpful in my case as it could be. I implemented `asset_exists?`, which in development uses `find_asset` instead. (From @amw's initial post, 🙏)

In my case, this code:
```ruby
<%= javascript_include_tag params[:controller] if asset_exists? "#{params[:controller]}.js" %>
```
caused a `Sprockets::Rails::Helper::AssetNotPrecompiled` error, which for me is more helpful (oh, right, need to go add this entrypoint to the manifest!) than silently not including the file.

```ruby
  def asset_exists? logical_path
    if Rails.configuration.assets.compile
      # Dynamic compilation
      Rails.application.assets.find_asset(logical_path).present?
    else
      # Pre-compiled
      Rails.application.assets_manifest.assets[logical_path].present?
    end
  end
```
