### ISSUE TITLE
v3.0.0 not loading correctly

### ISSUE THREAD

**Issue by zalmane** [rails/sprockets-rails#301]
Seems that V3.0.0 has broken some backwards functionality. I have been using jsrender-rails which adds a custom extension handler for Sprockets. It seems that somehow sprockets-rails is now not loaded first, causing the initializer of the other gem to get an empty applications.assets. I downgraded to V2.3.3 and it now works.

**Comment by matthewd** [comment]
That sounds like an issue in jsrender-rails.

**Comment by zalmane** [comment]
Yes and no. They have a line stating:
next unless app.assets
But the underlying bug is that app.assets should not have been empty since I assume sprockets needs to come first (or at least used to load first).
Is this by design?

**Comment by rafaelfranca** [comment]
> Seems that V3.0.0 has broken some backwards functionality.

Yes, it did. This is exactly why it was a major bump.

> But the underlying bug is that app.assets should not have been empty since I assume sprockets needs to come first (or at least used to load first).

Yes, it should be empty. `app.assets` (which is the Sprockets environment) is only present when you are asking to compile (which means `Rails.application.config.assets.compile = true`). It is set to `false` by default in Production, and that means that you don't have the Sprockets environment in production. It is one of the big changes in sprockets-rails 3. To avoid users unadvisedly compiling assets in production, the environment is not present anymore.

It is an issue in the jsrender-rails. The proper API to configure the sprockets environment is using `Rails.config.assets.configure` block, so they need to change the:

```
next unless app.assets
app.assets.register_engine(".jsr", Jsrender)
```

to:

```
app.config.assets.configure do |env|
  env.register_engine(".jsr", Jsrender)
end
```
