### ISSUE TITLE
JPEG extension is now forced to JPG

### ISSUE THREAD

**Issue by virgoproz** [rails/sprockets-rails#304]
Until 2.3.3, it was ok to have files JPEG using .jpeg or .jpg as extension.

From 3.0, JPEG are automatically converted to .jpg (both with actual precompilation and sandbox precompile errors). If you have something like image_tag('image.jpeg'), it breaks with the AssestNotPrecompiled error. Renaming the file to image.jpg will fix it.

Not a big deal for developers, refactoring filenames not a big ask :), just worth noting if this was not intentional.

**Comment by jdleesmiller** [comment]
Perhaps this is related to #246.

In case this saves someone else some time and head-scratching, I was getting
```
ActionView::Template::Error: Asset was not declared to be precompiled in production.
Add `Rails.application.config.assets.precompile += %w( resources/foo.jpeg )` to `config/initializers/assets.rb` and restart your server
```
from tests when rendering a view with a `image_tag 'resources/foo.jpeg'` helper. The problem went away when the file was renamed from `.jpeg` to `.jpg`. Downgrading to 2.3.3 also solved the problem.

It's also worth noting that if you follow the advice in the warning and add the resource to your precompile list, that does *not* help.

**Comment by schneems** [comment]
> just worth noting if this was not intentional.

I don't think it was intentional. Does anyone have a super small codetriage.com/example_app that shows this issue?

**Comment by david-mears** [comment]
@schneems I came across this issue in my hobby app today. I have stripped out everything apart from what is needed to demonstrate the issue, and I've put it in this repo:

https://github.com/david-mears/jpeg-issue-demo/commits/illustrate-jpeg-issue

I deployed it to https://sheltered-beach-99525.herokuapp.com/, which is up at the time of writing. Heroku hobby apps sleep when they haven't been touched for 30 minutes, so give it a minute to wake up.

I don't fully understand CodeTriage, so I'm not sure if I managed to submit it there.

Through trial and error, I discovered that only files ending .jpeg cause errors such as the below from my heroku logs:

```
ActionView::Template::Error (The asset "cups/goldcup.jpeg" is not present in the asset pipeline.
...
ActionView::Template::Error (The asset "cups/cup 8.jpeg" is not present in the asset pipeline.
...
ActionView::Template::Error (The asset "cups/chalice5.jpeg" is not present in the asset pipeline.
```

The bug can be 'fixed' either by renaming jpegs to jpgs, or by setting config.assets.compile = true
in production.rb.

**Comment by schneems** [comment]
> I don't fully understand CodeTriage, so I'm not sure if I managed to submit it there.

The link I provided has instructions on making an example app it looks like github didn't expand the link.

> or by setting config.assets.compile = true in production.rb.

To note: this will have performance issues and also opened a directory traversal security issue in an older version of sprockets. 

Thanks for the app!

**Comment by jrochkind** [comment]
As reported above for me breaks in *production*, but works fine in development. 

If you have an asset ending in `jpeg`, and reference it with eg Rails `image_tag("something.jpeg")` -- works fine in development, raises `Sprockets::Rails::Helper::AssetNotFound` in production. 

This is terribly confusing, not really documented anywhere as far as I know, and I just spent a few hours figuring it out -- and I am a very experienced Rails user. 

It would be acceptable (if not ideal) if it failed in both development and production, if `jpeg` was just not allowed as a suffix for some reason. But working in development and failing in production is pretty unforgiveable. It at least needs to be very clearly documented. 

That this is a long-running bug is making me question Sprockets viability.

**Comment by ajaleelp** [comment]
Took me a while to find this out! Anybody who can point me to the reason behind this? And totally agree with @jrochkind , it should atleast be warned about - especially given that it is not the same behaviour in development.

**Comment by pooriar** [comment]
This issue drove me insane today 😅

**Comment by unRARed** [comment]
Got me, too today. We just migrated away from Webpacker to jsbundling-rails with webpack and Sprockets. Per @jrochkind, at minimum the development experience should mirror production. Nothing worse than everything working great locally (where it's safe to fail) only to have it fail on production.

**Comment by ghiculescu** [comment]
I think https://github.com/rails/sprockets/pull/781 will fix this issue.

**Comment by brandondrew** [comment]
A bug from January 2016 is still biting people today?
