### ISSUE TITLE
Stack level error on assets_path with 3.0.0

### ISSUE THREAD

**Issue by IBazylchuk** [rails/sprockets-rails#309]
I have in gemfile 

sass-rails
bootstrap-rails
compass-rails
sprockets 3

when i back to sprockets-rails 2, it work fine

**Comment by rafaelfranca** [comment]
You need to give us more information on how to reproduce this issue, otherwise there is nothing we can do. Please read CONTRIBUTING.md file for more information about creating bug reports. Thanks!
