### ISSUE TITLE
Assets not being served after upgrade to sprockets-rails 3.0.0

### ISSUE THREAD

**Issue by psharpNumerex** [rails/sprockets-rails#312]
Upgraded the sprockets and sprockets-rails gems in my rails 4.2.5 app and now assets are not being served on the staging/production environments.

assets:precompile works as expected and all assets are seen in the public/assets directory, but a look at the source shows the page trying to fetch assets from /images or /stylesheets instead of /assets

config.assets.compile = false

when changed to 

config.assets.compile = true

enabled the assets when deployed and the path is not /assets as expected.

Is this the expected behavior or have we borked something during the upgrade?

**Comment by rafaelfranca** [comment]
It is the expected behavior. Your application is depending in the assets being compiled so you need to enabled the option.

**Comment by psharpNumerex** [comment]
So just for my own clarity:

I've always thought the compile flag meant "if you look for my asset in public/assets and you don't find it, then compile it on the fly"

But what it means now is "you need to look for the assets in public/assets instead of images/javascripts/stylesheets and if it's not there, then compile it on the fly"

Is that correct?

**Comment by rafaelfranca** [comment]
No, the behavior of the flag is still "if you look for my asset in public/assets and you don't find it, then compile it on the fly".

The change in the behavior was that it tried to find the asset in `public/assets` but it didn't find them and as the on the fly compilation is disabled it just fallback to `images` in case of images and `stylesheets` in case of css.

**Comment by psharpNumerex** [comment]
So this is where I'm confused then because the image/js/css IS in public/assets, compiled and fingerprinted, but isn't being served.

**Comment by psharpNumerex** [comment]
This is exactly the issue.  If debug = true and compile = false then I see the default Rails paths to assets (images/stylesheets/javascripts).

I've usually had debug on in staging, I found it helpful to see the digest AND know where items came from.

**Comment by vipulnsward** [comment]
@psharpNumerex can you create an example App with this issue?

**Comment by rafaelfranca** [comment]
If that is the case you can just set the value of the resolver manually. `config.assets.resolve_with = [:manifest]`

**Comment by psharpNumerex** [comment]
OK, I think have a deeper understanding of what's going on now and I'll be turning off debug on staging unless I need it and then can manually set the resolver.

Thanks for all the help!
