### ISSUE TITLE
Logger option is ignored during precompile

### ISSUE THREAD

**Issue by radar** [rails/sprockets-rails#314]
I'm trying to debug a slow precompile on my app here which has gone from 3 minutes to 5 minutes. I want a list of assets that it's trying to precompile. There is currently no output at all when I run `rake assets:precompile`, and I'm guessing that's because I have the wrong log level set on the logger.

I [read on the internet](http://stackoverflow.com/questions/19325039/how-to-debug-a-rails-asset-precompile-which-is-unbearably-slow/19371813#19371813) that you can do this with configuration like this:

```
Rails.application.config.assets.configure do |env|
  logger = Logger.new("log/assets.log")
  logger.level = Logger::DEBUG
  env.logger = logger
end
```

However, when the precompile task is ran, it's [wrapped in `with_logger`](https://github.com/rails/sprockets-rails/blob/9ef1ac55b5c22a77bec2552f175bd02f574084a0/lib/sprockets/rails/task.rb#L65-L70).

This method is defined in Sprockets and [actively discards this logger option to replace it with the default logger](https://github.com/rails/sprockets/blob/af3f3e114f8c2e27bb0ab27c060c1c359754548f/lib/rake/sprocketstask.rb#L142-L150).

How do I tell Sprockets / sprockets-rails to stop doing this?

**Comment by vipulnsward** [comment]
Configure `$stderr` to logger? :trollface: 

On a serious note, looks like it hasn't changed since https://github.com/vipulnsward/sprockets/commit/590e8b1a247ba3a750876e2a884270a06a6d6fc8
and was not intended for these tasks.
We should probably rely on default manifest logger.

**Comment by rafaelfranca** [comment]
> There is currently no output at all when I run rake assets:precompile

The default output is the stderr. Usually if there is no output it is because the files are already precompiled.

To change the logger you can define your own precompile tasks and setting `logger=`

```ruby
Rake::SprocketsTask.new do |t|
  t.logger = Logger.new("log/assets.log")
end
```
