### ISSUE TITLE
Sprockets-rails 3.0 breaks Bootstrap-sass gem

### ISSUE THREAD

**Issue by maximski** [rails/sprockets-rails#317]
Updating to 3.0 my Rails installation would mock me about missing $navbar-height variable from the Bootstrap-sass gem. Going back to 2.3.3 fixed the issue immediately.

**Comment by rafaelfranca** [comment]
That can be an incompatibility between bootstrap-sass and sprockets-rails 3. Could you open an issue in the bootstrap-sass project? It seems more an issue there that in sprockets-rails.
