### ISSUE TITLE
Problem with Precompiled assets after updating from 2.3.3 ->  3.0.0

### ISSUE THREAD

**Issue by whithajess** [rails/sprockets-rails#319]
I have run into a problem with updating my application from 2.3.3 -> 3.0.0 for sprocket rails.

I have tests that run `get :index` that now fail with 

```ruby
Failure/Error: get :index
ActionView::Template::Error:
  Asset was not declared to be precompiled in production.
  Add "Rails.application.config.assets.precompile += %w( html5shiv.js )" to "config/initializers/assets.rb" and restart your server
```

I have had a look at the https://github.com/rails/sprockets/blob/master/UPGRADING.md document and haven't seen anything there that helps.

Adding `Rails.application.config.assets.precompile += %w( html5shiv.js )` does not fix the problem. The file already has `Rails.application.config.assets.precompile += %w(timeout/* html5shiv/dist/html5shiv.js)`

It is being included In the .erb view files by
```ruby
<!--[if lt IE 9]>
  <%= javascript_include_tag 'html5shiv' %>
<![endif]-->
```

Removing this causes my tests to pass but I'm guessing this would break the functionality
any help would be much appreciated as this is a requirement of the recent security patches.

**Comment by rafaelfranca** [comment]
Could you try the master branch?

**Comment by whithajess** [comment]
Fixed in master

Found workaround using the fuller path
```ruby
  <!--[if lt IE 9]>
    <%= javascript_include_tag 'html5shiv/dist/html5shiv.js' %>
  <![endif]-->
```

**Comment by rafaelfranca** [comment]
Thank you for confirming. It will be fixed in the next version.
