### ISSUE TITLE
Remove hard coded cache/temporary path

### ISSUE THREAD

**Issue by squirly** [rails/sprockets-rails#322]
The cache directory used by sprockets-rails is hard coded. See: [lib/sprockets/railtie.rb:101](https://github.com/rails/sprockets-rails/blob/172fb4259611d0720c90dfa9836df06c1a600cb4/lib/sprockets/railtie.rb#L101)

This sucks and should be changed. See [SO: Change temporary directory in Rails 4](http://stackoverflow.com/questions/35077463/change-temporary-directory-in-rails-4/) for details.

**Comment by prathamesh-sonpatki** [comment]
It was changed in https://github.com/rails/sprockets-rails/commit/ecaeb27.

@schneems @rafaelfranca Should we support `config.assets.cache_store` back? I can take a stab at it but I don't know the reason behind it's removal.

**Comment by prathamesh-sonpatki** [comment]
@squirly It's configurable, check http://edgeguides.rubyonrails.org/asset_pipeline.html#assets-cache-store.
