### ISSUE TITLE
Sprockets temp folder will cause precompiling to use wrong assets.prefix

### ISSUE THREAD

**Issue by carsonreinke** [rails/sprockets-rails#325]
Using local precompilation and [config.assets.prefix](http://guides.rubyonrails.org/asset_pipeline.html#local-precompilation), such as `/dev-assets` will compile production assets using the wrong asset path (`/dev-assets`).  This is caused from the Sprockets cache folder `tmp/cache/assets/sprockets`.  Using a development site and development assets will create this cache folder.

Removing this folder before doing precompiling fixes the problem.  Maybe the Rake task `assets:precompile` should depend on `tmp:clear` or something like that.

How to reproduce:
1. Clear the cache first `rake tmp:clear`
2. In `config/environments/development.rb` change to `config.assets.prefix = "/dev-assets"`
3. Use asset pipeline in development
4. Precompile assets `env RAILS_ENV=production rake assets:precompile`
5. Search precompiled assets: `grep -R -e '/dev-assets' public/assets`

**Comment by modosc** [comment]
what about using the rails env as part of the cache key?

**Comment by PeterMozesMerl** [comment]
+1 for using the env as part of the key.

Please don’t run tmp:clear. For many applications, it’s needed to have different assets for each environment. There are various reasons, browser testing (Capybara) is one of them.

**Comment by carsonreinke** [comment]
Thanks @rafaelfranca !
