### ISSUE TITLE
rake assets:clobber task doesn't clear cache 

### ISSUE THREAD

**Issue by modosc** [rails/sprockets-rails#326]
the docs say:

```
Two cleanup tasks. rake assets:clean is now a safe cleanup that only removes older assets that are no longer used. While rake assets:clobber nukes the entire public/assets directory and clears your filesystem cache. The clean task allows for rolling deploys that may still be linking to an old asset while the new assets are being built.
```

but `clobber` only removes `public/assets`: 

https://github.com/rails/sprockets/blob/3.x/lib/sprockets/manifest.rb#L294

what's the expected behavior here? does it make sense to add `tmp:cache:clear` as a dependency for the `assets:clobber` task?

**Comment by rafaelfranca** [comment]
We want to clear the cache to be an exceptional case, so we don't want to make it part of the `assets:clober` task
