### ISSUE TITLE
precompile with Proc does not work

### ISSUE THREAD

**Issue by modosc** [rails/sprockets-rails#328]
(filed here because i think it's similar to https://github.com/rails/sprockets-rails/issues/269 - lmk if i should move it) 

i have this in a rails application:
```
  # workaround https://github.com/rails/rails/issues/11759
  config.assets.precompile << Proc.new { |path, fn| fn =~ /vendor\/assets/ && !%w(.js .css).include?(File.extname(path)) }
```
when i upgrade `sprockets` from `3.5.1` to `4.0.0.beta` i get this error on `assets:precompile`:
```
NoMethodError: undefined method `start_with?' for #<Proc:0x007fe4e3f62f78>
/Users/jon/.rvm/gems/ruby-2.3.0@vouch_web/bundler/gems/sprockets-0de36bbee349/lib/sprockets/uri_utils.rb:75:in `valid_asset_uri?'
/Users/jon/.rvm/gems/ruby-2.3.0@vouch_web/bundler/gems/sprockets-0de36bbee349/lib/sprockets/resolve.rb:26:in `resolve'
/Users/jon/.rvm/gems/ruby-2.3.0@vouch_web/bundler/gems/sprockets-0de36bbee349/lib/sprockets/base.rb:64:in `find_asset'
/Users/jon/.rvm/gems/ruby-2.3.0@vouch_web/bundler/gems/sprockets-0de36bbee349/lib/sprockets/base.rb:73:in `find_all_linked_assets'
/Users/jon/.rvm/gems/ruby-2.3.0@vouch_web/bundler/gems/sprockets-0de36bbee349/lib/sprockets/manifest.rb:124:in `block in find'
/Users/jon/.rvm/gems/ruby-2.3.0@vouch_web/bundler/gems/sprockets-0de36bbee349/lib/sprockets/manifest.rb:123:in `each'
/Users/jon/.rvm/gems/ruby-2.3.0@vouch_web/bundler/gems/sprockets-0de36bbee349/lib/sprockets/manifest.rb:123:in `find'
/Users/jon/.rvm/gems/ruby-2.3.0@vouch_web/bundler/gems/sprockets-0de36bbee349/lib/sprockets/manifest.rb:165:in `compile'
/Users/jon/.rvm/gems/ruby-2.3.0@vouch_web/bundler/gems/sprockets-rails-907cf04e92c3/lib/sprockets/rails/task.rb:69:in `block (3 levels) in define'
/Users/jon/.rvm/gems/ruby-2.3.0@vouch_web/bundler/gems/sprockets-0de36bbee349/lib/rake/sprocketstask.rb:147:in `with_logger'
/Users/jon/.rvm/gems/ruby-2.3.0@vouch_web/bundler/gems/sprockets-rails-907cf04e92c3/lib/sprockets/rails/task.rb:67:in `block (2 levels) in define'
/Users/jon/.rvm/gems/ruby-2.3.0@vouch_web/gems/bugsnag-3.0.0/lib/bugsnag/rake.rb:12:in `execute_with_bugsnag'
```

**Comment by rafaelfranca** [comment]
Precompile procs doesn't work in sprockets 4 anymore. Only strings. You should be moving to the manifest file.

https://github.com/rails/sprockets/blob/master/UPGRADING.md#manifestjs

**Comment by modosc** [comment]
could you add an explicit notice about this (and the regex deprecation) in the upgrade docs? both are common idioms and it's unclear that sprockets 4 is explicitly deprecating them since `config.assets.precompile` works basically the same otherwise.

**Comment by rafaelfranca** [comment]
@schneems is working on this. BTW, this is deprecated since sprockets 3. The manifest works there.

**Comment by modosc** [comment]
it's working fine on `3.5.1` without any deprecation notice in the logs for me. also the rails guides still mention a `Proc` being legit:

http://edgeguides.rubyonrails.org/asset_pipeline.html#precompiling-assets

granted rails-edge specifies `'sprockets-rails', '>= 2.0.0'` but since it's not explicitly in the sprockets 3 or 4 guides i can see it causing issues for people beyond me.

**Comment by schneems** [comment]
Sprockets doesn't have any deprecation messages ATM. We will fix that someday. We should explicitly deprecate proc. Try out 4.0.0.beta2 and sprockets-rails 3.0.2
