### ISSUE TITLE
Document changed default of config.assets.digest?

### ISSUE THREAD

**Issue by Aqualon** [rails/sprockets-rails#330]
I just updated sprockets-rails in an app from 2.3.3 to 3.0.2 and got some failing tests due to unexpected fingerprints in URLs generate by image_url helper.

After some digging around I found, that default value of config.assets.digest was changed to true in https://github.com/rails/sprockets-rails/commit/3cb84ea29aa321c97364dca86e5685f1ed447df2

Should this be documented somewhere?

**Comment by rafaelfranca** [comment]
Thanks. I documented in the changelog https://github.com/rails/sprockets-rails/releases/tag/v3.0.0
