### ISSUE TITLE
undefined method `start_with?' 

### ISSUE THREAD

**Issue by KeithP** [rails/sprockets-rails#333]
Running Rails 5.0.0.beta3 
Having upgraded to sprockets-rails (3.0.2) and sprockets (4.0.0.beta2) we get this error, possibly similar to #269 ?

undefined method `start_with?' for /font-awesome\/fontawesome-webfont\.(?:eot|svg|ttf|woff|woff2?)$/:Regexp

Extracted source (around line #10):

    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>

sprockets (4.0.0.beta2) lib/sprockets/uri_utils.rb:75:in `valid_asset_uri?'
sprockets (4.0.0.beta2) lib/sprockets/resolve.rb:26:in `resolve'
sprockets (4.0.0.beta2) lib/sprockets/base.rb:64:in `find_asset'
sprockets (4.0.0.beta2) lib/sprockets/base.rb:73:in `find_all_linked_assets'
sprockets (4.0.0.beta2) lib/sprockets/manifest.rb:124:in `block in find'
sprockets (4.0.0.beta2) lib/sprockets/manifest.rb:123:in `each'
sprockets (4.0.0.beta2) lib/sprockets/manifest.rb:123:in `find'
sprockets-rails (3.0.3) lib/sprockets/railtie.rb:49:in `each'
sprockets-rails (3.0.3) lib/sprockets/railtie.rb:49:in `map'
sprockets-rails (3.0.3) lib/sprockets/railtie.rb:49:in `precompiled_assets'
sprockets-rails (3.0.3) lib/sprockets/railtie.rb:34:in `asset_precompiled?'
sprockets-rails (3.0.3) lib/sprockets/railtie.rb:213:in `block (3 levels) in <class:Railtie>'
sprockets-rails (3.0.3) lib/sprockets/rails/helper.rb:345:in `call'
sprockets-rails (3.0.3) lib/sprockets/rails/helper.rb:345:in `precompiled?'
sprockets-rails (3.0.3) lib/sprockets/rails/helper.rb:349:in `raise_unless_precompiled_asset'
sprockets-rails (3.0.3) lib/sprockets/rails/helper.rb:334:in `find_debug_asset'
sprockets-rails (3.0.3) lib/sprockets/rails/helper.rb:216:in `block in lookup_debug_asset'
sprockets-rails (3.0.3) lib/sprockets/rails/helper.rb:229:in `block in resolve_asset'
sprockets-rails (3.0.3) lib/sprockets/rails/helper.rb:228:in `each'
sprockets-rails (3.0.3) lib/sprockets/rails/helper.rb:228:in `detect'
sprockets-rails (3.0.3) lib/sprockets/rails/helper.rb:228:in `resolve_asset'
sprockets-rails (3.0.3) lib/sprockets/rails/helper.rb:215:in `lookup_debug_asset'
sprockets-rails (3.0.3) lib/sprockets/rails/helper.rb:157:in `block in stylesheet_link_tag'
sprockets-rails (3.0.3) lib/sprockets/rails/helper.rb:156:in `map'
sprockets-rails (3.0.3) lib/sprockets/rails/helper.rb:156:in `stylesheet_link_tag'

**Comment by rafaelfranca** [comment]
Dup of https://github.com/rails/sprockets-rails/issues/269
