### ISSUE TITLE
3.x generates the same assets for each environment which breaks features

### ISSUE THREAD

**Issue by PeterMozesMerl** [rails/sprockets-rails#334]
2.x generates separated assets for the Rails environments (development, test, production). Which is awesome. In test environment, I can use way lower setTimeout() parameters than in production so Capybara features don’t fail due to timeout.

I can also mark the advert boxes in development mode with slightly different CSS so I can see what is supposed to be here and there. Not to forget fixed size advert boxes in development, which isn’t good for responsive ad units in production. 

One has to create sass.erb and coffee.erb assets to make these work.

However, 3.x generates the same asset for test and development environments. It’s upgrade-breaking when the application uses dynamic assets.

**Comment by rafaelfranca** [comment]
Thank you for the report. This is a dup of https://github.com/rails/sprockets-rails/issues/325

**Comment by bughit** [comment]
@rafaelfranca 

The asset cache does not appear to be partitioned by environment, it's all in  tmp/cache/assets/sprockets/v3.0

Does partitioning no longer require separate folders?
