### ISSUE TITLE
Check if all assets compiled?

### ISSUE THREAD

**Issue by hendricius** [rails/sprockets-rails#337]
I would like to know if all assets have been successfully compiled. Is there a way to check for exactly that?

I need to do a health check on my rails application if it is ready to accept new traffic. For that I would also like to double check that all assets have been precompiled and are ready to be served.

Thanks!

**Comment by aditya-kapoor** [comment]
i think the current implementation of the sprockets does that, however if you are still not satisfied with solution then check out this [gem](https://github.com/alexspeller/non-stupid-digest-assets).

**Comment by hendricius** [comment]
What is the method I have to use in order to find this out? :)

**Comment by rafaelfranca** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.

**Comment by hendricius** [comment]
Alrighty. Ok thanks!
