### ISSUE TITLE
Bug: Chart rendering on staging

### ISSUE THREAD

**Issue by gemfarmer** [rails/sprockets-rails#340]
On [staging](https://micropurchase-staging.18f.gov/auctions/winners) there is a soft bug that looks like this in the console. It is likely caused by the circles being defined in the "Auctions by bid" chart not having a valid (likely undefined) bid amount.
<img width="508" alt="screen shot 2016-04-12 at 3 03 36 pm" src="https://cloud.githubusercontent.com/assets/4803473/14473897/f4832d4e-00bf-11e6-9685-805528e036e9.png">

**Comment by vipulnsward** [comment]
@gemfarmer Any sprockets issue here?

**Comment by rafaelfranca** [comment]
You need to give us more information on how to reproduce this issue, otherwise there is nothing we can do. Please read CONTRIBUTING.md file for more information about creating bug reports. Thanks!

**Comment by gemfarmer** [comment]
@vipulnsward @rafaelfranca I'm sorry. I meant to post this in a different repo 😦
