### ISSUE TITLE
Assets compilation is too long in development and test

### ISSUE THREAD

**Issue by sevaorlov** [rails/sprockets-rails#345]
Hi, it is said here http://guides.rubyonrails.org/asset_pipeline.html#live-compilation that sprockets now compiles all the assets on first request, isn't that a huge work to do on first request? 

I'm updating an app form Rails 3 to Rails 4 and encountered the problem that first request in  development takes about 20 minutes and the same for tests. On CI our tests just fails by timeout.

I see that this line https://github.com/rails/sprockets-rails/blob/master/lib/sprockets/railtie.rb#L49 triggers manifest to load all assets, is that intended or I'm doing something wrong?

Thanks.

**Comment by sevaorlov** [comment]
I use rails 4.2.6, sprockets 3.6.0, sprockets-rails 3.0.4.

**Comment by sevaorlov** [comment]
isn't that possible to check if asset is included in precompile without loading and precompile all the assets?

**Comment by rafaelfranca** [comment]
Unfortunately no. I'm working to improve the performance of this but compiling in the first request is expected behavior.
