### ISSUE TITLE
Rails 5 has deprecated alias_method_chain

### ISSUE THREAD

**Issue by phaza** [rails/sprockets-rails#346]
Rails 5 deprecates alias_method_chain and as such the route wrapper is now causing deprecation warnings on the rails console:
https://github.com/rails/sprockets-rails/blob/master/lib/sprockets/rails/route_wrapper.rb#L18

**Comment by rafaelfranca** [comment]
That only happens when `prepend` is not defined. See https://github.com/rails/sprockets-rails/commit/f3558797a230ded556939eecf82f7f6ae759608c. Is it still happen? Could you create an sample application reproducing the bug?

**Comment by tisba** [comment]
Maybe I'm misreading the commit, but it doesn't look like `alias_method_chain` is called conditionally.

**Comment by swaps19** [comment]
agree with @tisba

**Comment by rafaelfranca** [comment]
Yes, it is https://github.com/rails/sprockets-rails/commit/f3558797a230ded556939eecf82f7f6ae759608c#diff-b295f4f07d2e863f15e53eb2047cfd1fR156. `alias_method_chain` is only called in the `included` callback and `included` callback is only called when `include` is used to `include` the module. As `include` is only called when `prepend` is not defined, `alias_method_chain` is only called when `prepend` is not defined.
