### ISSUE TITLE
[Readme Stuff]: Some articles on Sprockets Internals

### ISSUE THREAD

**Issue by ilatif** [rails/sprockets-rails#353]
Hi @schneems. I just watched your **RailsConf 2016** talk (Saving Sprockets) and I' am really impressed with the overall theme of the talk. You are right that in-order to keep a project healthy and sustainable, developers using those projects should step ahead and start contributing.

I had written 04 articles on Sprockets' internals 02 years ago. Following are the links to those articles:

- [How Asset Precompile Works, Part I](https://www.sitepoint.com/asset-precompile-works-part/)

- [How Asset Precompile Works, Part II](https://www.sitepoint.com/asset-precompile-works-part-ii/)

- [Sprockets Dissected: Asset Tags](https://www.sitepoint.com/sprockets-dissected-asset-tags/)

- [Sprockets Dissected: Rack and Middleware](https://www.sitepoint.com/sprockets-dissected-rack-middleware/)

Above mentioned articles discuss internals of Sprockets in a great detail. First article focuses on how Sprockets compile `StaticAssets` and how it assigns digest based on file content. Second article elaborates how Sprockets handles JavaScript and Stylesheet assets and how `require` and related stuff work. Third article focuses on how Sprockets inserts assets tags i.e. `<script>`, `<link>`, `<img>` etc. in `development` and `production` environments. Fourth articles explores how Sprockets serves assets. All above articles are based on `Sprockets 2.2.2`.

The purpose of creating this issue is, **Contributing**. I mean, internals of Sprockets might not have changed much since `Sprockets 2.2.2` and anyone who wants to get involved with Sprockets can get a lot of information by reading just those 04 articles. If you think it as appropriate, then can those articles be included in the *Readme* file or at some other appropriate location in Sprockets' docs?

Thanks

**Comment by schneems** [comment]
Thanks for opening an issue! I love these articles. I might need to reference them as Sprockets 2.x is still technically supported (however it's in unofficial maintenance mode).

> internals of Sprockets might not have changed much since Sprockets 2.2.2

Unfortunately quite a bit has changed. Many of the internal concepts are pretty different, while some have persisted. Without an in depth effort it would be pretty difficult. I'm hesitant to link in Sprockets 4 (master) or 3 (branch 3.x) to these for risk of confusing someone who wants to reference docs and finds inconsistencies between articles and code. I would love for you to look over some of the existing guides at https://github.com/rails/sprockets/tree/master/guides and see if you have any questions, comments, or additions. 

If you're interested in updating some of the articles for Sprockets 3+ Ruby Source (sitepoint) might be interested in running them but you would need to check with them first. I know one of the editors Glenn, and he's pretty decent to work with, not sure who you worked with previously. If they get updated we could probably add a links section or maybe find appropriate places in the existing documentation to link out to.

Thanks for reaching out. Let me know if you have any follow up questions ❤️

**Comment by ilatif** [comment]
Thanks for your comment. I' am really excited and nervous as it's my first time interacting directly with a Ruby Hero 😓  😰 .

You are right, I was suspecting that things might have changed since Sprockets 2.2.2 but still I thought that I should share my hard work with you 😄 .

Yeah, I have worked with Glenn as he is editor for RubySource and you are absolutely right, he is quite an awesome person to work with. I' am a bit hesitant to write about Sprockets 3+ internals because I have observed that most of the people reading articles on sites like RubySource don't like articles on internals 😞  and I learned this thing the hard way. Maybe I' am wrong with this observation, but I have closely inspected this thing many times.

Thanks for pointing towards Sprockets docs, I would love to read them and will do my best to contribute in every possible way I could.

Thanks ❤️ .

**Comment by schneems** [comment]
>  I' am really excited and nervous as it's my first time interacting directly with a Ruby Hero 😓 😰 .

I put on my pants the same way as everyone else, with a sophisticated set of pulleys compressed air and arduino powered robots.

I agree with ruby source and internals, it's a bit over the heads of many of the base readers. They want more actionable stuff.

In other news I got the talk from Rafael Franca transcribed, if you have free time I could use help getting it polished into a proper document with code examples etc. https://github.com/rails/sprockets/issues/308 if that doesn't sound like your cup of tea, no worries. Thanks again for reaching out.

**Comment by rafaelfranca** [comment]
> In other news I got the talk from Rafael Franca transcribed

OMG! This is huge. I'll do that.
