### ISSUE TITLE
SRI should apply to 127.0.0.1 as well

### ISSUE THREAD

**Issue by robinwhittleton** [rails/sprockets-rails#361]
The SRI `integrity` helper currently [checks to see whether the host is secure](https://github.com/rails/sprockets-rails/blob/master/lib/sprockets/rails/helper.rb#L192) and doesn’t apply if not. That’s good in general, but local development should be special-cased for testing purposes. [The spec says](https://www.w3.org/TR/SRI/#non-secure-contexts-remain-non-secure):

>it is recommended that authors deliver integrity metadata only to a [Secure Context](https://w3c.github.io/webappsec-secure-contexts/)

which says (in the [`localhost` section](https://w3c.github.io/webappsec-secure-contexts/#localhost)) that `127.0.0.1` should (well, SHOULD/MAY) also be treated as a ‘Secure Context’ for the purposes of the spec. This would help debugging / development.

**Comment by connorshea** [comment]
Also ran into this problem, I had to generate myself a cert for localhost, very ugly hack >.>

**Comment by connorshea** [comment]
Actually, looking at the spec it seems that the SSL requirement is no longer necessary:

https://www.w3.org/TR/SRI/#is-response-eligible-for-integrity-validation

**Comment by robinwhittleton** [comment]
Reading that thoroughly, I think what they’re saying is that it’s possible for integrity validation to work in a non-secure context (as a general concept), but that for the security requirements of this specific spec a ‘Secure Context’ (titlecase, defined) is needed.

**Comment by robinwhittleton** [comment]
This is fixed by https://github.com/rails/sprockets-rails/pull/362 then.

**Comment by rafaelfranca** [comment]
@robinwhittleton yeah, kinda. I was just looking the spec and indeed it is recommended to not seliver the integrity check in a non secure context. I'll change that patch to only allow localhost.

**Comment by robinwhittleton** [comment]
I think `localhost` specifically is disallowed, only `127.0.0.1` is valid: https://w3c.github.io/webappsec-secure-contexts/#localhost

**Comment by connorshea** [comment]
Per https://www.chromium.org/Home/chromium-security/deprecating-powerful-features-on-insecure-origins, Chrome treats localhost as secure, and it's my understanding that Firefox does the same.
