### ISSUE TITLE
Asset path generated in scss helper methods has duplicated asset prefix

### ISSUE THREAD

**Issue by Levara** [rails/sprockets-rails#363]
Hi, I think this behaviour is a bug.

I'm having problems with asset prefix. If I configure `Rails.application.config.assets.prefix = 'myprefix'`
in `config/initializers/assets.rb`, and then run: 
```
RAILS_ENV=production rake assets:clobber
RAILS_ENV=production rake assets:precompile
```
all my precompiled assets get generated with correct path (`public/myprefix/asset_digest.png`). Finding assets from .erb file works correctly, the path is correctly generated and everything is shown correctly. The problem is that paths generated in `image-url()` and similar methods in .scss files get prefix two times. 

So instead of `public/myprefix/background_digest.jpg` Rails is trying to find the image at the `public/myprefix/myprefix/background_digest.jpg`, but the image is correctly precompiled and saved to `public/myprefix` folder. One workaround is to simply copy all assets from `myprefix` to `myprefix/myprefix`, but it's a nasty way to deal with this. This happend only for assets referenced from .scss files.

To be sure it's not a problem with my configuration I tried to reproduce it on new application: 
Ruby: 2.3.0
Rails: 4.2.6.
```
rails new prefixtext -T
cd prefixtest
rails generate scaffold post title body:string
```
configured:
- root route for posts#index
- one css rule in `application.scss`:  
```
.background {
  width: 500px;
  height: 500px;
  background-image: image-url('my-background.jpg');
}
```
- div with .background class added to posts index view
- migrate db
- assets:clobber and assets:precompile
- start server
- all commands are prefixed with `RAILS_ENV=production`

I also tried with sprockets-rails version 2.3.2, and the same thing happens. 

My machine is ArchLinux with rvm, buddy also tried on his machine (last Ubuntu also with rvm) and same thing happens on my server (CentOs 7 with rvm). 
Tested Ruby versions: 2.3.0, 2.1.2, 2.1.5.; tested Rails versions: 4.2.1, 4.2.6

I never did any development on Rails itself before, I'd like to try to fix this myself but I don't know where to start. 

If any more info is needed, please feel free to ask.

**Comment by cilim** [comment]
You forgot to put a slash in the prefix! :)

So just write:
`Rails.application.config.assets.prefix = '/myprefix'`

and everything should work fine.

**Comment by rafaelfranca** [comment]
I just tried the same thing and adding the slash in the prefix made it work correctly.
