### ISSUE TITLE
config.assets.quiet = true not working

### ISSUE THREAD

**Issue by aried3r** [rails/sprockets-rails#364]
The way I understood the feature is that it would replace the quiet_assets gem, right?

If so, it doesn't seem to work for me, I see all assets requests in the log:

```
Started GET "/assets/landing/banner/1920@2x-999c853019ce78c0fabd51f7258c17056ed78b3f7447a8cf51a7cc81d64e26b7.jpg" for 127.0.0.1 at 2016-06-28 10:22:00 +0200
```

Ruby 2.3.1
Rails 4.2.6
sprockets-rails 3.1.0 (`gem 'sprockets-rails', '~> 3.1', require: 'sprockets/railtie'`)

```Ruby
# config/initializers/assets.rb

# Suppresses logger output for asset requests.
Rails.application.config.assets.quiet = true
```

```Ruby
# rails console
> Rails.application.config.assets.prefix
=> "/assets"
```

**Comment by rafaelfranca** [comment]
It is due to a bug in rails that is fixed in rails 4-2-stable branch. Thank you for the report.

**Comment by rafaelfranca** [comment]
Ah, also make sure the config is in development.rb otherwise it will not be applied.

**Comment by aried3r** [comment]
> Ah, also make sure the config is in development.rb otherwise it will not be applied.

Good point, thanks! Is that implied somewhere? I could not find it in the README or the code itself after a quick glimpse.

Shouldn't it "just work" within an initializer, though?

**Comment by aried3r** [comment]
> It is due to a bug in rails that is fixed in rails 4-2-stable branch.

https://github.com/rails/rails/pull/25341 this one fixes it, right? Do you happen to know if there'll be a minor release soon?

**Comment by rafaelfranca** [comment]
> Good point, thanks! Is that implied somewhere?

It is documented in the Rails source code. It generates in development.rb

> Shouldn't it "just work" within an initializer, though?

It doesn't. `config/initializers` run after all railties initiliazers so when the initializer run the sprockets-rails railtie will already be executed. 

> rails/rails#25341 this one fixes it, right? Do you happen to know if there'll be a minor release soon?

Right. No I don't know when will be the minor release yet.
