### ISSUE TITLE
NoMethodError `silence` on Logger instance

### ISSUE THREAD

**Issue by morgoth** [rails/sprockets-rails#366]
I'm using Rails 5 with rails-sprockets 3.1.1

I'm having `config.assets.quiet = true` in development env, but also custom logger set:
```ruby
if ENV["RAILS_LOG_TO_STDOUT"].present?
  config.logger = ActiveSupport::TaggedLogging.new(Logger.new(STDOUT))
end
```

I'm getting errors, as `ActiveSupport::TaggedLogging.new(Logger.new(STDOUT))` doesn't respond to method `silence`

**Comment by rafaelfranca** [comment]
Thank you for the report. The fix to this is to use a log that respond to `silence`.

**Comment by rafaelfranca** [comment]
Just to be clear this feature is made to work with loggers that respond to `silence` we don't plan to make it work with loggers that are not the default Rails logger in development.

**Comment by westonganger** [comment]
I had to change this:

`config.logger = Logger.new(config.paths['log'].first, 100, 104857600)`

to this to make it work.

`config.logger = ActiveSupport::Logger.new(config.paths['log'].first, 100, 104857600)`

@morgoth So maybe try to change `Logger` to `ActiveSupport::Logger` in your case

**Comment by topazas** [comment]
Well it was kinda my fault. 
For information purposes, check other config files ;( 
In my case Jekyll config was overwriting my config logger.
