### ISSUE TITLE
Quiet option is not working

### ISSUE THREAD

**Issue by dwradcliffe** [rails/sprockets-rails#367]
We just upgraded to the latest (3.1.1) gem and enabled the new quiet option but it doesn't seem to be working.

```
Started GET "/assets/jquery.color.self-6aa31e05b411418a032e6455b0cf79457f5d45ba3a6fe501f1f508d84d0eebcc.js?body=1" for ::1 at 2016-07-01 20:14:58 -0400


Started GET "/assets/clipboard.self-848fb35751b7071135f0ba385a38dbc562ba2baf12c345fb929cf467687ed9be.js?body=1" for ::1 at 2016-07-01 20:14:58 -0400


Started GET "/assets/announcements.self-a26c620532b3a53f9647680eafa0613953d1964d9d50018168c4997f2a147365.js?body=1" for ::1 at 2016-07-01 20:14:58 -0400


Started GET "/assets/clipboard_buttons.self-81e653811225b31aefcfe499e478be6d5aa6ce80f6254bb22eec9b63b38f623c.js?body=1" for ::1 at 2016-07-01 20:14:58 -0400


Started GET "/assets/mobile-nav.self-b1aa8d9ea2df9a14f63b147fda128ba0e5930b09bc2e85a00db5f8fbe424e065.js?body=1" for ::1 at 2016-07-01 20:14:58 -0400


Started GET "/assets/popup-nav.self-761ccafb8ce1594988091037a3dd3e0e7d0efa52194b9285896ff22e6027ac69.js?body=1" for ::1 at 2016-07-01 20:14:58 -0400


Started GET "/assets/application.self-705575bc483598bd0d9c3be0db390d8ca6e05bda2687beaa2e080cbc592b3f0c.js?body=1" for ::1 at 2016-07-01 20:14:58 -0400
```

https://github.com/rubygems/rubygems.org/commit/f32321d52c83f7c9979a60858e38d866b27ac41d

@rafaelfranca @kmcphillips

**Comment by kmcphillips** [comment]
I can have a look tomorrow!

**Comment by rafaelfranca** [comment]
You need Rails 4.2.7.rc1 to have it working

**Comment by kmcphillips** [comment]
@dwradcliffe @levilansing

So. If you look in `development.log` you will find that the logging is indeed being stripped. But the replacement `quiet = true` option uses `ActiveSupport::Logger#silence` to suppress logging. There was unfortunately a bug in all versions of rails that caused `silence` to not work correctly when being changed via `broadcast`. The `broadcast` module is what is used to output requests to both the console and the log.

The fix to logging is in Rails 5 and was backported to 4.2 stable. https://github.com/rails/rails/pull/25341 https://github.com/rails/rails/pull/25397

**Comment by connorshea** [comment]
4.2.7 is out, should this be closed?
