### ISSUE TITLE
JST only available pre-3.0.0 ? 

### ISSUE THREAD

**Issue by jasonfb** [rails/sprockets-rails#368]
Was JST deprecated in 3.0.0? We are seeing some evidence in a Rails 4.1 -> 4.2 upgrade that JST templates are unavailable (JST is undefined in javascript), and were led to believe from this post: http://stackoverflow.com/questions/31975445/uncaught-referenceerror-jst-is-not-defined-on-rails-4  that locking Sprockets into 2.3.3 was the only current solution to this.

Please advise if JST is supported past 2.3.3 or if another solution is needed

**Comment by rafaelfranca** [comment]
No. JST is supported in sprockets 3+ https://github.com/rails/sprockets/tree/3.x#javascript-templating-with-ejs-and-eco
