### ISSUE TITLE
rails 5 config.assets.quiet does not work

### ISSUE THREAD

**Issue by topazas** [rails/sprockets-rails#370]
In development.rb is set config.assets.quiet = true
And all assets respond with: 

> NoMethodError: undefined method `silence' for #<Logger:0x007f517a752830>
> lib/ruby/gems/2.3.0/gems/sprockets-rails-3.1.1/lib/sprockets/rails/quiet_assets.rb:11:in `call'

sprockets-rails 3.1.1

**Comment by kaspth** [comment]
`assets.quiet` requires a standard Rails logger, which is an instance of `ActiveSupport::Logger` 😁

It'll work if you change your logger to an instance of that. Thanks!

**Comment by topazas** [comment]
Can You explain a little more? I haven't changed Logger to a different.

**Comment by topazas** [comment]
Explicitly set in config

>   config.logger = ::Logger.new(STDOUT)
>   config.log_level = :debug

The same error.

**Comment by kaspth** [comment]
I'm saying try `config.logger = ActiveSupport::Logger.new(STDOUT)` 😁

**Comment by topazas** [comment]
```
  config.logger = ActiveSupport::Logger.new(STDOUT)
  config.log_level = :debug
  config.assets.quiet = true
```

Same error.

**Comment by kaspth** [comment]
Changing to Active Support logger is the correct fix: https://github.com/rails/sprockets-rails/issues/366

I'm not sure what else to tell you, but I won't be doing remote tech support. Have a nice day!

**Comment by devvmh** [comment]
I also have this issue. It doesn't appear to be the same problem as #366 because I'm not getting the same error message. That poster said

> I'm getting errors, as ActiveSupport::TaggedLogging.new(Logger.new(STDOUT)) doesn't respond to method silence

but I haven't experienced that.

I have added a line to my initializers, and running `rails c` I get this output:

```
[1] pry(main)> Rails.application.config.logger
=> #<ActiveSupport::Logger:0x007fe83d4855a8
 @default_formatter=#<Logger::Formatter:0x007fe83d485530 @datetime_format=nil>,
 @formatter=#<ActiveSupport::Logger::SimpleFormatter:0x007fe83d485418 @datetime_format=nil>,
 @level=0,
 @local_levels=#<Concurrent::Map:0x007fe83d4853c8 entries=0 default_proc=nil>,
 @logdev=
  #<Logger::LogDevice:0x007fe83d485468
   @dev=#<IO:<STDOUT>>,
   @filename=nil,
   @mon_count=0,
   @mon_mutex=#<Thread::Mutex:0x007fe83d485440>,
   @mon_owner=nil,
   @shift_age=nil,
   @shift_size=nil>,
 @progname=nil>
[2] pry(main)> Rails.application.config.logger.respond_to?(:silence)
=> true
[3] pry(main)> Rails.application.config.assets.quiet
=> true
```

However, I still can't get my assets to be quiet.

Any thoughts?

**Comment by viveks1422** [comment]
config.logger = Logger.new(STDOUT)
config.log_level = :debug
