### ISSUE TITLE
require jquery in multiple manifests

### ISSUE THREAD

**Issue by collimarco** [rails/sprockets-rails#373]
This is my `application.js`:

```
//= require jquery
//= require jquery_ujs
//= require_tree .
//= stub subscriptions
```
It has always worked as expected and `subscription.js` is another file which is compiled separately.

If I add this line at the top of `subscriptions.js`:

```
//= require jquery
```

The `subscriptions.js` is compiled as expected, but jQuery disappears from `application.js`.
This means that you cannot require jquery in multiple manifest files.

I am using a development environment with Rails 4.2.4 + Puma and the default `jquery-rails` gem.

**Comment by rafaelfranca** [comment]
This is the expected behavior of `stub`. All dependencies inside the file that is stubbed will not be added. If all you want is to not include subscriptions inside application.js it is recommended to not use `require_tree`.

https://github.com/rails/sprockets#the-stub-directive
