### ISSUE TITLE
sprockets-rails 3.1.1 precompiles all assets in development

### ISSUE THREAD

**Issue by dfritsch86** [rails/sprockets-rails#374]
I have a rails application with huge amounts of assets due to some frontend frameworks. In `config/initializers/assets.rb` I use wildcard selectors to precompile all assets for production.

When starting the rails sever for development, the first request takes forever, presumably because all assets are being precompiled. This seems to happen only with the newer versions of sprockets-rails (3.1).

Older versions of sprockets-rails (2.3.3) would load just fine. My feeling is that older versions would not compile all the assets greedily, but only when needed, while never versions seem to compile them all upfront. 

Is this behaviour intended?

I made a [small example app](https://github.com/dfritsch86/possible_sprockets_rails_issue) to demonstrate the issue.

**Comment by rafaelfranca** [comment]
Duplicated of https://github.com/rails/sprockets-rails/issues/352
