### ISSUE TITLE
NoMethodError: undefined method 'silence' for #<Logger:...>

### ISSUE THREAD

**Issue by rossta** [rails/sprockets-rails#376]
Thanks for all the hard work on `sprockets-rails`! 💜💜💜

Here's my issue:
### Environment
- sprockets-rails 3.1.1
- rails 5.0.0.1
- ruby 2.3
### Actual behavior

In development, when using a `Rails.logger` that does not respond to `#silence`, all requests for assets fail, throwing `NoMethodError: undefined method`silence' for ...`. (See below for stacktrace).
### Expected behavior

It looks like [the recent introduction](https://github.com/rails/sprockets-rails/commit/830e2d9c15fb1506f4b39c5b9b81ffd48f7c0534) of `Sprockets::Rails::QuietAssets` expect the `Rails.logger` to include the `LoggerSilence` module. Unfortunately, many examples, such as in [this blog post](http://blog.bigbinary.com/2016/04/12/rails-5-allows-to-send-log-to-stdout-via-environment-variable.html), demonstrate use of the stdlib `Logger`, which does not include `LoggerSilence`, as `Rails.logger`, for example, to log to `STDOUT`:

``` ruby
if ENV["RAILS_LOG_TO_STDOUT"].present?
  config.logger = ActiveSupport::TaggedLogging.new(Logger.new(STDOUT))
end
```

Perhaps we could instead log a warning in development at asset response time when enabling `config.assets.silence` without a compliant logger. 
### Stacktrace

``` bash
web    | 2016-08-26 21:19:30 -0400: Rack app error handling request { GET /assets/turtle-logo-120x120-ae484afcc7fd91bf02307479480a4944bbb876d1b0313cd4d42bbd0aba74dabc.png }
web    | #<NoMethodError: undefined method `silence' for #<Logger:0x007f89081dbad0>>
web    | /Users/ross/.gem/ruby/2.3.1/gems/sprockets-rails-3.1.1/lib/sprockets/rails/quiet_assets.rb:11:in `call'
web    | /Users/ross/.gem/ruby/2.3.1/gems/newrelic_rpm-3.16.2.321/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
web    | /Users/ross/.gem/ruby/2.3.1/gems/actionpack-5.0.0.1/lib/action_dispatch/middleware/request_id.rb:24:in `call'
web    | /Users/ross/.gem/ruby/2.3.1/gems/newrelic_rpm-3.16.2.321/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
web    | /Users/ross/.gem/ruby/2.3.1/gems/rack-2.0.1/lib/rack/method_override.rb:22:in `call'
web    | /Users/ross/.gem/ruby/2.3.1/gems/newrelic_rpm-3.16.2.321/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
web    | /Users/ross/.gem/ruby/2.3.1/gems/rack-2.0.1/lib/rack/runtime.rb:22:in `call'
web    | /Users/ross/.gem/ruby/2.3.1/gems/newrelic_rpm-3.16.2.321/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
web    | /Users/ross/.gem/ruby/2.3.1/gems/activesupport-5.0.0.1/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
web    | /Users/ross/.gem/ruby/2.3.1/gems/newrelic_rpm-3.16.2.321/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
web    | /Users/ross/.gem/ruby/2.3.1/gems/actionpack-5.0.0.1/lib/action_dispatch/middleware/executor.rb:12:in `call'
web    | /Users/ross/.gem/ruby/2.3.1/gems/newrelic_rpm-3.16.2.321/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
web    | /Users/ross/.gem/ruby/2.3.1/gems/actionpack-5.0.0.1/lib/action_dispatch/middleware/static.rb:136:in `call'
web    | /Users/ross/.gem/ruby/2.3.1/gems/newrelic_rpm-3.16.2.321/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
web    | /Users/ross/.gem/ruby/2.3.1/gems/rack-2.0.1/lib/rack/sendfile.rb:111:in `call'
web    | /Users/ross/.gem/ruby/2.3.1/gems/newrelic_rpm-3.16.2.321/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
web    | /Users/ross/.gem/ruby/2.3.1/gems/railties-5.0.0.1/lib/rails/engine.rb:522:in `call'
web    | /Users/ross/.gem/ruby/2.3.1/gems/newrelic_rpm-3.16.2.321/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
web    | /Users/ross/.gem/ruby/2.3.1/gems/puma-3.6.0/lib/puma/configuration.rb:225:in `call'
web    | /Users/ross/.gem/ruby/2.3.1/gems/puma-3.6.0/lib/puma/server.rb:578:in `handle_request'
web    | /Users/ross/.gem/ruby/2.3.1/gems/puma-3.6.0/lib/puma/server.rb:415:in `process_client'
web    | /Users/ross/.gem/ruby/2.3.1/gems/puma-3.6.0/lib/puma/server.rb:275:in `block in run'
web    | /Users/ross/.gem/ruby/2.3.1/gems/puma-3.6.0/lib/puma/thread_pool.rb:116:in `block in spawn_thread'
```

**Comment by logicminds** [comment]
I was also getting this error after I endabled logging to STDOUT in my development environment. Once I removed this setting, everything worked as expected: ` config.logger = Logger.new(STDOUT)`

**Comment by jscho13** [comment]
For those who are still experiencing this problem when trying to run your rails app locally the fix is to add the following to your `development.rb` file.
```
logger           = ActiveSupport::Logger.new(STDOUT)
logger.formatter = config.log_formatter
config.logger = ActiveSupport::TaggedLogging.new(logger)
```
You'll notice you have a similar configuration in your `production.rb` file.

**Comment by mandysimon88** [comment]
@jscho13 Is that the same solution for production and test environments as well or just development?

**Comment by jscho13** [comment]
It worked for my production environment as well. I have never tried in a test environment, but I can think of no reason why it wouldn't work.

**Comment by aquadrehz** [comment]
You solution is great @jscho13 
I also found working around as well 

`config.logger = ActiveSupport::Logger.new('/dev/null')`

Ref :
https://stackoverflow.com/questions/38760235/unable-to-serve-static-assets-on-rails-5-0-super-no-method-silence-for-lo
https://stackoverflow.com/questions/41539844/rails-app-assets-not-being-loaded-on-development-environment

Should we **add this configure to the configure generator as well?**
I found this issue when trying to upgrade from Rails **5.1 to 5.2**
But it do not throw anything. Just Error 500 when try to get asset **"application.debug-<some_hash_string>"**

<img width="1132" alt="Screen Shot 2564-03-04 at 19 33 54" src="https://user-images.githubusercontent.com/3850078/109964758-abd1a200-7d20-11eb-8ad9-11f98f3e070b.png">
