### ISSUE TITLE
Access Rails.application.assets when compile=false

### ISSUE THREAD

**Issue by codebycliff** [rails/sprockets-rails#385]
We are in the process of upgrading from rails 4.2 to 5. When upgrading sprockets-rails, we ran into an issue relating to the [Disable Rails.application.assets when compile=false](https://github.com/rails/sprockets-rails/pull/220/files) PR. 

We want `Rails.application.assets.compile = false` so that assets are not compiled on each request; however, we have a feature that depends on the sprockets environment (`Rails.application.assets`) for manually compiling themes on demand. Is there a way to get access to the sprockets environment without having `compile` set to true?

**Comment by rafaelfranca** [comment]
No, there is not. If we add access to the environment when compile is false missing files at production will compiled on each request.

**Comment by codebycliff** [comment]
To clarify, that is not the case in sprockets-rails < 3 correct? Currently on version 2.3.3, we have `compile` set to false and we have access to the sprockets environment and it doesn't appear to compile missing files on each request.

**Comment by rafaelfranca** [comment]
No, that is not the case. If you have access to the environment in production and you have a call like `Rails.application.assets.find_asset` you care compiling in production.

**Comment by codebycliff** [comment]
Well, yes, if I call it explicitly for a given request. That's not the scenario I am talking about. We have a background job called `ThemeCompiler` that uses the sprockets environment to precompile the assets (with some custom variables) and save the generated stylesheet in s3, which the rest of the app then consumes. A background job calling `find_asset` shouldn't mean that asset compilation is happening on all web requests on a completely different server right? Either way, I was able to add the following line to our service object to get it working with `compile=false`:

```
@sprockets_env = Rails.application.assets || Sprockets::Railtie.build_environment(Rails.application)
```

**Comment by rafaelfranca** [comment]
Yeah, in that case you should not bother to disable compile at all. If you call `rake assets:precompile` before deploying and you have the static assets generated sprockets is not going to compile them in every request. In the end `compile` option is only to control if you are going to have a sprockets environment in production or not.

**Comment by codebycliff** [comment]
That is good to know! I read a [stackoverflow post](http://stackoverflow.com/questions/8821864/config-assets-compile-true-in-rails-production-why-not) that said even if all assets are precompiled, there is still a negative performance impact due to the _lookup_ (not necessarily compilation) that sprockets has to make for each asset request.

> On subsequent requests Sprockets receives the request and has to look up the fingerprinted filename, check that the file (image) or files(css and js) that make up the asset were not modified, and then if there is a cached version serve that.

> That is everything in the assets folder and in any vendor/assets folders used by plugins.

> That is a lot of overhead as, to be honest, the code is not optimized for speed.

> This will have an impact on how fast asset go over the wire to the client, and will negatively impact the page load times of your site.

That post is pretty old (4 years), but I'm wondering if those statements still apply or if the answer needs updating?

**Comment by rafaelfranca** [comment]
The answer needs to be updated. If you have the assets precompiled the ruby proccess is not even reached when the request for the asset is made.
