### ISSUE TITLE
Asset logging not disabled after upgrading to rails 4

### ISSUE THREAD

**Issue by mb-dev** [rails/sprockets-rails#40]
I see this article about asset logging in rails 4:
http://blog.remarkablelabs.com/2012/12/sprockets-rails-rails-4-countdown-to-2013

After upgrading to rails 4 beta today, I still see logs in my console:

Started GET "/assets/bootstrap-datepicker.js?body=1" for 127.0.0.1 at 2013-03-03 13:58:32 -0800
Started GET "/assets/gmaps.js?body=1" for 127.0.0.1 at 2013-03-03 13:58:32 -0800
Started GET "/assets/items.js?body=1" for 127.0.0.1 at 2013-03-03 13:58:32 -0800
Started GET "/assets/lib/jquery.extensions.js?body=1" for 127.0.0.1 at 2013-03-03 13:58:32 -0800
Started GET "/assets/lib/jquery.glass.js?body=1" for 127.0.0.1 at 2013-03-03 13:58:32 -0800
Started GET "/assets/lib/jquery.overlay.js?body=1" for 127.0.0.1 at 2013-03-03 13:58:32 -0800
Started GET "/assets/messages.js?body=1" for 127.0.0.1 at 2013-03-03 13:58:32 -0800
Started GET "/assets/omniauth_callbacks.js?body=1" for 127.0.0.1 at 2013-03-03 13:58:32 -0800
Started GET "/assets/pages.js?body=1" for 127.0.0.1 at 2013-03-03 13:58:33 -0800
Started GET "/assets/payments.js?body=1" for 127.0.0.1 at 2013-03-03 13:58:33 -0800
Started GET "/assets/rentals.js?body=1" for 127.0.0.1 at 2013-03-03 13:58:33 -0800
....

Is there something I need to do to disable the logging after upgrade?

**Comment by jchanfnet** [comment]
I'm using https://github.com/evrone/quiet_assets to suppress asset logs on my Rails 4.2.2 project.
