### ISSUE TITLE
Emblem-rails assets are not properly precompiled

### ISSUE THREAD

**Issue by nachootal** [rails/sprockets-rails#402]
I had this system running that I upgraded from rails 4.1.8 to 4.2.8. As soon as I did that, the recompilation of the assets is failing. Nothing else changed in the assets side so I understand there's some assets that are not properly identified as to be precompiled

I'm attaching the error as it is output in [https://hastebin.com/fihawonebu.vbs](here) and I set up a rails app that reproduces the error [https://github.com/nachootal/failing_sprockets_ember_assets.git](here).

How else can I help debugging this?. I'm a bit lost with this error since it was previously compiling fine and the assets are just the same. I don't know very well the asset pipeline but I'm eager to help and learn.

**Comment by rafaelfranca** [comment]
This is an issue in emblem-rails. Could you open an issue there?
