### ISSUE TITLE
Rails.application.assets is nil in production even during precompilation

### ISSUE THREAD

**Issue by mrsimo** [rails/sprockets-rails#407]
First of all, I'm aware of https://github.com/rails/sprockets-rails/issues/237 and I think I understand the reasoning. I wanted to explain our use case and see if it makes sense.

We have a situation where we want to embed a `platform.css` inside a `platform.js`. For this, in Rails 4 we used `<%= Rails.application.assets['platform.css'].to_s %>`. We can't switch to `Rails.application.assets_manifest.find_sources` because the `platform.css` isn't there the very first time you run `assets:precompile`.

We solved this issue by initializing a sprockets environment, using:

```ruby
Sprockets::Railtie.build_environment(Rails.application, true)['platform.css'].to_s
```

Even though `assets.compile` is false, I would have expected that `Rails.application.assets` is available during the `assest:precompile` rake task. It is the production environment, but it's also the precompilation task.

I wonder if you'd reconsider this use case and if we can find an alternative. Thanks.

**Comment by rafaelfranca** [comment]
Does changing your code to `<%= depend_on_asset('platform.css').source %>` works?

**Comment by mrsimo** [comment]
Oh, my. Had no idea `depend_on_asset` existed. It seems to work! Apologies for the noise and thanks for the solution!

**Comment by rafaelfranca** [comment]
No problem 😄. You can see all methods on that context here http://www.rubydoc.info/gems/sprockets/Sprockets/Context
