### ISSUE TITLE
Option config.assets.compile = false not working

### ISSUE THREAD

**Issue by overallduka** [rails/sprockets-rails#410]
This option is in README and is totally useless in Rails 5+ ..also the admin of project close this topic without solve: 

https://github.com/rails/sprockets-rails/issues/49 

This is relevant today yet. Is a needed for many people.

**Comment by rafaelfranca** [comment]
I think you misunderstood, `compile = false` is to disable assets compilation and it does work right now. #49 is about adding digests to the file name and we don't have a way to do it anymore. There are a lot of ways to do that already in the conversation in the issue you linked.

Also, we closed that issue for a reason, please don't open new issues about the same thing.
