### ISSUE TITLE
Path traversal patch conflicts with existing dependencies

### ISSUE THREAD

**Issue by hananamar** [rails/sprockets-rails#430]
The patch regarding the latest [Path Traversal vulnerability in Sprockets](http://seclists.org/oss-sec/2018/q2/210) has been implemented in release version `2.12.5` of Sprockets. However, Rails `3.2.22.5` depends on Sprockets version `2.2.1`.

**Comment by matthewd** [comment]
https://github.com/rails/rails/issues/33169#issuecomment-398752636
