### ISSUE TITLE
Has this been patched for the security vulnerability to use the latest sprockets?

### ISSUE THREAD

**Issue by sumeetattree** [rails/sprockets-rails#431]
[In relation to this](https://blog.heroku.com/rails-asset-pipeline-vulnerability) I still see that the sprockets version listed is '>= 3.0.0' and heroku recommends upgrading to '3.7.2'. Is this going to be addressed?

**Comment by rafaelfranca** [comment]
>= 3.0.0 allows any version greater than 3.0.0 and this includes 3.7.2. Gems that have dependencies don't need to be updated every time one of its dependencies have security issues. This is why applications have their Gemfile and Gemfile.lock and it is the application responsibility to make sure it is using secure dependencies.

**Comment by sumeetattree** [comment]
Got it. Thanks!
