### ISSUE TITLE
gemspec pulls in sprockets 4.x

### ISSUE THREAD

**Issue by Fryguy** [rails/sprockets-rails#443]
At present, the gemspec is open ended [1] on the sprockets version and with the release of sprockets 4.0, that version automatically gets pulled in.

While the specs in this gem pass locally when I switch to 4.x by modifying the Gemfile [2], our application is failing with the following error:

```text
rails aborted!
Sprockets::Railtie::ManifestNeededError: Expected to find a manifest file in `app/assets/config/manifest.js`
But did not, please create this file and use it to link any assets that need
to be rendered by your app:

Example:
  //= link_tree ../images
  //= link_directory ../javascripts .js
  //= link_directory ../stylesheets .css
```

For now we pinned our app's sprockets dependency to 3.x and we are ok.  However this gem bringing in the new sprockets may not be desirable, and I'm not sure the right path forward (pin and release or cut a major version of sprockets-rails), so I'm opening this issue.

[1] https://github.com/rails/sprockets-rails/blob/master/sprockets-rails.gemspec#L16
[2] https://github.com/rails/sprockets-rails/blob/master/Gemfile#L8

**Comment by rafaelfranca** [comment]
Thank you for the report. This gem supports both sprockets 3 and sprockets 4. We even test against it.

That error you see is an error in your application that you need to fix in order to use sprockets 4.

**Comment by Fryguy** [comment]
My concern is that the open-ended nature of the gemspec dep causes it to get pulled in, and it's not "compatible" without app changes.

**Comment by Samsinite** [comment]
I'm getting this same error as well, can we reopen this issue? Seems like a bug to me and would lie to better understand why it is not.

**Comment by rafaelfranca** [comment]
It is not a bug. This gem work with both sprockets 3 and sprockets 4. It is possible that you app don't work with sprockets 4. In that case you either need to make it work by following https://github.com/rails/sprockets/blob/master/UPGRADING.md#guide-to-upgrading-from-sprockets-3x-to-4x, or change you gemfile to lock the sprockets version.

**Comment by Samsinite** [comment]
Locked for now, thanks for specifying the guide, can't believe I didn't notice it in the comment above. Sorry for the trouble

**Comment by krisleech** [comment]
> or change you gemfile to lock the sprockets version.

`gem 'sprockets', '~>3.0'`

**Comment by hadees** [comment]
I get the reason it breaks but it is kind of annoying that an update for `rspec-rails` would totally break my test environment because of a change in sprocket.  I guess this is a larger Ruby where people don't properly set version constraints for gems.

**Comment by rafaelfranca** [comment]
The constraints are properly set in all gems. This is more a problem in bundler that you can solve easily by using the `--conservative` option when updating gems.
