### ISSUE TITLE
"Expected to find a manifest file" error with assets disabled

### ISSUE THREAD

**Issue by delner** [rails/sprockets-rails#444]
With the release of Sprockets 4.0 and the requirement of a `manifest.js` file, we're seeing an error similar to #443 with `sprockets-rails` 3.2.1 where our test suite is producing this error:

```
/usr/local/bundle/gems/sprockets-rails-3.2.1/lib/sprockets/railtie.rb:105:in `block in <class:Railtie>': Expected to find a manifest file in `app/assets/config/manifest.js` (Sprockets::Railtie::ManifestNeededError)
But did not, please create this file and use it to link any assets that need
to be rendered by your app:

Example:
  //= link_tree ../images
  //= link_directory ../javascripts .js
  //= link_directory ../stylesheets .css
and restart your server
```

We load the standard `require 'rails/all'` in our test suite (which loads sprockets 4.0 by default), but we have no interest in using Sprockets or the asset pipeline within it.

If we disable Sprockets with `config.assets.enabled = false` in our application, we expect that we shouldn't need to have a `manifest.js` file. However, merely having `require 'sprockets/railtie'` anywhere in your application will force this check to occur unconditionally, regardless of if you've disabled the the application pipeline:

https://github.com/rails/sprockets-rails/blob/v3.2.1/lib/sprockets/railtie.rb#L103-L110

```ruby
initializer :set_default_precompile do |app|
  if using_sprockets4?
    raise ManifestNeededError unless ::Rails.root.join("app/assets/config/manifest.js").exist?
    app.config.assets.precompile += %w( manifest.js )
  else
    app.config.assets.precompile += [LOOSE_APP_ASSETS, /(?:\/|\\|\A)application\.(css|js)$/]
  end
end
```

I would suggest changing this check to be based conditionally on whether assets are enabled or not, so users are not forced to completely remove `sprocket-rails` to disable it.

**Comment by rafaelfranca** [comment]
The proper way to fix this is stop using `require 'rails/all'` and not load `sprockets/rails` in your application.

**Comment by delner** [comment]
This is not an option for us; we need all the default Rails components other than Sprockets, and to have to update our `require '*/railtie'` statements every time Rails adds new components (e.g. ActionText, ActionMailbox) because `sprockets-rails` doesn't want to check whether its actually enabled or seems like a bad experience for Rails users who `gem 'rails'`.

**Comment by rafaelfranca** [comment]
The way Rails let you opt-out components is by requiring individual railties. Railties are added once a year, you don't need a lot of work to add require statements once a year. There is no other option, sorry.

**Comment by delner** [comment]
If preventing `require 'sprockets/railtie'` is the only way to disable Sprockets, then what is the purpose of `config.assets.enabled = false`?

**Comment by rafaelfranca** [comment]
That is for disabling compilation of assets. That doesn't disable the sprockets-rails to be loaded or executed.

**Comment by matthewmath** [comment]
Just curious, the path is sprockets 3.2.1, why is `using_sprockets4?` now returning true and dropping into the required manifest code?

**Comment by rafaelfranca** [comment]
sprockets is different of sprockets-rails. The path is sprockets-rails-3.2.1

**Comment by denys-husiev** [comment]
I have this error just because I need to `require 'sprockets/railtie'` for using graphiql-rails gem.  And to fix it, I should add manifest.js file to my rails api project. Seems a little weird :)

**Comment by hugoh59** [comment]
How do you solve this error?

**Comment by andreynering** [comment]
I could solve it by running:

```bash
mkdir -p app/assets/config && echo '{}' > app/assets/config/manifest.js
```

**Comment by matyapiro31** [comment]
So, what is the cause of this error?
I didn't find this message before 2019, so there were some change that let this error happen.

**Comment by alejandrocen** [comment]
For Rails api only:

In file: `config/application.rb`

Uncomment:
`require 'sprockets/railtie'`


Create `app/assets/config/manifest.js` and add this:

```
//= link graphiql/rails/application.css
//= link graphiql/rails/application.js
```

My `Gemfile`

```
...
gem 'graphql', '~> 1.10'

group :development do
  ...
  gem 'graphiql-rails', '~> 1.7'
end
```

**Comment by arianf** [comment]
> The way Rails let you opt-out components is by requiring individual railties. Railties are added once a year, you don't need a lot of work to add require statements once a year. There is no other option, sorry.

@rafaelfranca Is there a list of `railties` that I can replace `require 'rails/all'` with for my version of rails?

**Comment by arianf** [comment]
Never mind found it: https://github.com/rails/rails/blob/5-1-stable/railties/lib/rails/all.rb

(replace 5-1) with your version

**Comment by mperham** [comment]
This is shockingly un-empathetic from the Rails team. Look at the number of linked issues this has generated. I have 3-4 test Rails apps in my test suites, every one broke when I upgraded rails in my Gemfile. My apps were generated years ago with `rails new`. Can we not have better fallback behavior?

**Comment by dbackeus** [comment]
An alternative approach to avoiding this issue would be to lock `sprockets-rails` to pre 4.x by explicitly adding:

```ruby
gem "sprockets", "<4"
```

To your `Gemfile`.

Judging by the gemspec, Rails 6 is still compatible with both sprockets 2.x and 3.x.

**Comment by Br3nda** [comment]
here's how I finally upgraded rails on an older open source rails app

added this to `app/assets/config/manifest.js`
```
//= link_tree ../images
//= link_directory ../javascripts .js
//= link_directory ../stylesheets .css
```

and then re-ran `bundle exec rails assets:precompile`

**Comment by joelcahalan** [comment]
I had to pin an API only rails app to sprockets less than 4. Despite not requiring sprockets in application.rb it was still somehow being loaded and causing an error.

**Comment by sobrinho** [comment]
Got bitten by this one more time today.

**Comment by swapnilchincholkar** [comment]
Faced the same issue with API only app with rails(v 6.0.3.3), ruby(v 2.7.1). Required to do both of the following,

1. Uncommented `require "sprockets/railtie"` from `config/application.rb`
2. And [creating empty manifest file](https://github.com/rails/sprockets-rails/issues/444#issuecomment-548526846) as said by @andreynering

**Comment by mayankdedhia** [comment]
> 
> 
> An alternative approach to avoiding this issue would be to lock `sprockets-rails` to pre 4.x by explicitly adding to your `Gemfile`:
> 
> ```ruby
> gem "sprockets", "<4"
> ```
> 
> Judging by the gemspec, Rails 6.0 is still compatible with both sprockets 2.x and 3.x.

Just doing this worked for my API only app

**Comment by gingerlime** [comment]
sorry for another "me too", but I'm really confused why this happens even for a rails app that doesn't use sprockets any more. We:

* removed the gem
* remove `require "rails/all"`
* commented out `require "sprockets/railtie"`
* removed our manifest.json since we no longer use it

Normally rails runs fine, but when we run, e.g. `bundle exec rake db:test:prepare` we get this error because the manifest.json is missing

I understand the workaround with an empty json file, but this still means that some process is running / checking this file, when it shouldn't if sprockets is disabled. Right?

**Comment by omarsotillo** [comment]
I know this is closed but I found kind of the issue at least for me ( I was upgrading from 5.2 to 6.0 and swap into webpacker) ! 

**After digging into it it was related with** [sassc rails](https://github.com/sass/sassc-rails/issues/150). It is using sprockets under the hood

My approach: 
- Remove `sassc-rails` or find alternative 
- Remove all references to assets
- Remove `tmp/assets` folder
- Remove `app/assets`

Maybe it works for some of you :)

cc @gingerlime @mayankdedhia @swapnilchincholkar

**Comment by omarsotillo** [comment]
Also recommended by @ahorek [here](https://github.com/sass/sassc-rails/issues#issuecomment-747291727) (did not try myself)

>  just change
> 
> //= require applicationtest.sass
> to
> 
> //= require applicationtest

**Comment by yonyossef** [comment]
```
Expected to find a manifest file in `app/assets/config/manifest.js` (Sprockets::Railtie::ManifestNeededError)
But did not, please create this file and use it to link any assets that need
```

Hi, can anyone tell me if the manifest.js file link is hard coded in sprockets, or it can be changed to a different location?
Can I change it from app/assets/config/manifest.js to lib/assets?
Thx

**Comment by kevinmtrowbridge** [comment]
This monkeypatch will allow the behavior to be changed (perhaps introducing other problems ... use only after thinking about the tradeoffs):

```
module Sprockets
  class Railtie < ::Rails::Railtie
    initializer :set_default_precompile_manifest_optional, after: :set_default_precompile do |app|
      # Find original method here: https://github.com/rails/sprockets-rails/blob/master/lib/sprockets/railtie.rb#L103
      p "sprockets_monkeypatch_make_manifest_optional.rb"
      app.config.assets.precompile += %w( manifest.js )
    end
    # https://dev.to/st0012/how-to-replace-a-rails-initializer-30n0
    initializers.reject! { |i| i.name == :set_default_precompile }
  end
end
```
