### ISSUE TITLE
header control when config.assets.compile = true 

### ISSUE THREAD

**Issue by arivero** [rails/sprockets-rails#449]
Could it be possible to add somewhere an option to set the headers of assets produced when the compile option is true? I mean, the not-precompiled ones.

I think that now they are produced with the same cookies and headers that any other request routed into rails, which includes the session cookie.

**Comment by rafaelfranca** [comment]
Please use StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
