### ISSUE TITLE
Error when precompiling HTML ERb files

### ISSUE THREAD

**Issue by chrisledet** [rails/sprockets-rails#45]
### Background

Our error pages use the same stylesheets as our Rails application. We need to be able to point to these stylesheets from our error pages. I moved the error pages into `app/assets/pages`, and would like them precompiled so we can accomplish this. This solution works fine in development mode where the assets are generated on the fly. However, it breaks precompiling from the command line using any Rails environment.
### Error

When I run `bundle exec rake assets:precompile` inside my Rails 4 app's directory, I receive the following error:

```
undefined local variable or method 'debug_assets' for #<#<Class:0x007fdba5bd0>:0x007fdba41ed8>
```

I have HTML ERb files inside my `app/assets/pages` directory and told Rails about them by doing the following: 

```
module MyApp
  class Application < Rails::Application
    config.assets.paths << "#{Rails.root}/app/pages/html"
    config.assets.precompile += %w(404.html 500.html)
  end
end
```

Here's the stack trace + HTML ERb file:
https://gist.github.com/chrisledet/b8bb3765dc61f0d532cb

Seems like the error is coming from:
https://github.com/rails/sprockets-rails/blob/master/lib/sprockets/rails/helper.rb#L130

**Comment by bronson** [comment]
fwiw, I packaged this technique into a gem: https://github.com/bronson/error_page_assets

Hope it helps others.  Discussion most welcome.
