### ISSUE TITLE
Timeout error: ::Sprockets::Railtie.build_environment(Rails.application).find_asset("#{params[:controller]}.css")

### ISSUE THREAD

**Issue by siddushar** [rails/sprockets-rails#453]
HI,

Im getting timeout errors while loading assets dynamically. 

ERROR: 
FATAL -- : Rack::Timeout::RequestTimeoutException (Request ran for longer than 15000ms):

 stylesheet_link_tag params[:controller] if (Rails.application.assets || ::Sprockets::Railtie.build_environment(Rails.application)).find_asset("#{params[:controller]}.css")
    = javascript_include_tag params[:controller] if (Rails.application.assets || ::Sprockets::Railtie.build_environment(Rails.application)).find_asset("#{params[:controller]}.js")
   

could you please suggest what can be done to fix the timeout error

**Comment by rafaelfranca** [comment]
Please use StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
