### ISSUE TITLE
Sprockets 4.0 — Not able to require font's from gem like bootstrap

### ISSUE THREAD

**Issue by StefanWallin** [rails/sprockets-rails#457]
First off all, thank you for this great piece of software! 🧁

### Description of Issue
My issue is that since the introduction of the manifest.js-solution I am not able(or knowing how) to include font-files provided by an external gem such as [bootstrap-sass](https://github.com/twbs/bootstrap-sass). I'm not sure if this is an issue with `sprockets-rails` or an issue with `bootstrap-sass` or `sass-rails`.

### I've made a reproduction case with this example app:
https://github.com/StefanWallin/sprockets-test-app

**I've split the commits as:**
- Initial rails
- Remove uneccesary things from rails
- [Problem reproduction commit](https://github.com/StefanWallin/sprockets-test-app/commit/349c820c415044a60a1849877128a12d38d3bee6)

### How to reproduce:
1. Boot up example-app
1. Request http://localhost:3000
1. You now get a 404 for the font-files referenced in the Sass-files.

### What is expected to happen:
An icon is presented on load top left corner instead of a square after the font-files are able to load.

### Screengrab of problem:
![Screenshot 2020-01-16 at 15 21 43](https://user-images.githubusercontent.com/457653/72532574-fd487480-3873-11ea-8f82-d86a048f622e.png)

### Stack trace:
```
ActionController::RoutingError (No route matches [GET] "/fonts/bootstrap/glyphicons-halflings-regular.ttf"):

actionpack (6.0.2.1) lib/action_dispatch/middleware/debug_exceptions.rb:36:in `call'
web-console (4.0.1) lib/web_console/middleware.rb:132:in `call_app'
web-console (4.0.1) lib/web_console/middleware.rb:28:in `block in call'
web-console (4.0.1) lib/web_console/middleware.rb:17:in `catch'
web-console (4.0.1) lib/web_console/middleware.rb:17:in `call'
actionpack (6.0.2.1) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (6.0.2.1) lib/rails/rack/logger.rb:38:in `call_app'
railties (6.0.2.1) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (6.0.2.1) lib/active_support/tagged_logging.rb:80:in `block in tagged'
activesupport (6.0.2.1) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (6.0.2.1) lib/active_support/tagged_logging.rb:80:in `tagged'
railties (6.0.2.1) lib/rails/rack/logger.rb:26:in `call'
sprockets-rails (3.2.1) lib/sprockets/rails/quiet_assets.rb:13:in `call'
actionpack (6.0.2.1) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (6.0.2.1) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.1.1) lib/rack/method_override.rb:24:in `call'
rack (2.1.1) lib/rack/runtime.rb:24:in `call'
activesupport (6.0.2.1) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (6.0.2.1) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.2.1) lib/action_dispatch/middleware/static.rb:126:in `call'
rack (2.1.1) lib/rack/sendfile.rb:113:in `call'
actionpack (6.0.2.1) lib/action_dispatch/middleware/host_authorization.rb:83:in `call'
webpacker (4.2.2) lib/webpacker/dev_server_proxy.rb:23:in `perform_request'
rack-proxy (0.6.5) lib/rack/proxy.rb:57:in `call'
railties (6.0.2.1) lib/rails/engine.rb:526:in `call'
puma (4.3.1) lib/puma/configuration.rb:228:in `call'
puma (4.3.1) lib/puma/server.rb:681:in `handle_request'
puma (4.3.1) lib/puma/server.rb:472:in `process_client'
puma (4.3.1) lib/puma/server.rb:328:in `block in run'
puma (4.3.1) lib/puma/thread_pool.rb:134:in `block in spawn_thread'
```

**Comment by rafaelfranca** [comment]
This is an issue on bootstrap-sass. They are still using the removed regular expression support on the precompile list https://github.com/twbs/bootstrap-sass/blob/b34765d8a6aa775816c59012b2d6b30c4c66a8e9/lib/bootstrap-sass/engine.rb#L12

**Comment by StefanWallin** [comment]
Thank you for the fast reply! 🤩  I'll try to make a PR with them then!
