### ISSUE TITLE
Error: Asset 'application.css' was not declared to be precompiled in production

### ISSUE THREAD

**Issue by john-999** [rails/sprockets-rails#458]
I'm getting the error:

    ActionView::Template::Error (Asset 'application.css' was not declared to be precompiled in production.
    Declare links to your assets in 'app/assets/config/manifest.js'.

      //= link application.css
    and restart your server):

But I have my `application.scss` (NOT .css) in `app/assets/stylesheets` and my `app/assets/config/manifest.js` says:

    //= link_tree ../images
    //= link_directory ../javascripts .js
    //= link_directory ../stylesheets .scss

I'm using:
- sprockets 4.0.0
- sprockets-rails 3.2.1
- rails 6.0.2.1

Temporary solution: Downgrade the gem as follows:

    gem 'sprockets-rails', '2.3.3'

**Comment by johnnorris** [comment]
I've also just had this same problem with the same versions, and the same temporary solution worked for me.

**Comment by rossinkiwi** [comment]
This manifests as a compile error for me.  Downgrading sprockets-rails version makes the issue go away.  See attached file for rails assets:precompile trace.  The trace seems to indicate a coffeescript error, but I have no coffeescript files in my app/assets/javascripts or gems akaik.

[assets_compile.txt](https://github.com/rails/sprockets-rails/files/4464964/assets_compile.txt)

**Comment by dimameshcharakou** [comment]
`rake tmp:clear` helped me.

**Comment by MichaelSeeberger** [comment]
Doing what the error told me worked. My `app/assets/config/manifest.js` now looks like this:
```
//= link_tree ../images
//= link application.css
```
I too have `application.scss` and not `application.css`.  I have the same versions, except rails is 6.0.2.2

**Comment by shanecav84** [comment]
For me, this was caused by a missing Javascript asset:

```javascript
// application.js
//= require missing_asset.js
```

I'd updated a third-party JS library, which had changed its path. Correcting the path fixed the problem. Weird that it had nothing to do with `application.css`.

**Comment by thebravoman** [comment]
Same problem, but with application.scss.erb.

Workaroud it with 
```
gem 'sprockets-rails', '2.3.3'
```

**Comment by roxannecojocariu** [comment]
Same problem for me.  Sprockets updated it's documentation to explain [why this is happening and how to fix it](https://github.com/rails/sprockets/blob/master/UPGRADING.md#manifestjs).  Essentially, you'll need to add subdirectories in your `app/assets/stylesheets`.  This solution is the only one that's worked for me so far.

**Comment by westonganger** [comment]
In my case `rake tmp:clear` did not work. I had to explicitly use `rm -rf tmp/*`

**Comment by danielricecodes** [comment]
> rake tmp:clear

Worked.  This should be added to the [original post](https://github.com/rails/sprockets-rails/issues/458#issue-577552623) as the solution since so many people have 👍'd it.  

The recommendation to downgrade `sprockets-rails` should be avoided.  A local problem that can be easily solved by flushing your `Rails.root/tmp` directory should not require making a commit and then unduly influencing every other environment, dev machine, CI system, etc.

**Comment by Flip437** [comment]
rake tmp:clear didn't work for me
downgrading to gem 'sprockets-rails', '2.3.3' with bundle install worked for me

**Comment by magedeungaro** [comment]
> `rake tmp:clear` helped me.

This helped me, thanks

**Comment by rstacruz** [comment]
I ran into this issue because I had a `//= require` in my application.js that didn't exist.

```js
/* app/assets/javascripts/application.js.erb */

//= require this-a-non-existent-asset
```

Removing it fixed the error for me.

**Comment by andosteinmetz** [comment]
I've had this issue come up occasionally and worked around it by adding an empty newline to `/app/assets/config/manifest.js` loading a page, and then reverting the change.

**Comment by rgaufman** [comment]
Any solution to this? - it is in my manifest.js but also seeing the same:

I'm using:
* ruby 3.1.3p185
* rails (7.0.4.2)
* sprockets (4.2.0)
* sprockets-rails (3.4.2)

**Comment by moxorama** [comment]
I'm trying to add couple of sass @imports in application.css and getting this message

**Comment by archonic** [comment]
On Rails 6, with `jsbundling-rails` and `cssbundling-rails`, my manifest.js was this:

```
//= link_tree ../images
//= link_tree ../builds
```

This was fine until I updated to Rails 7. I'm only getting the error in my CI though (CirlceCI).

rails 7.0.4.3
sprockets 4.2.0
sprockets-rails-3.4.2

**Comment by JaguarRocka** [comment]
On Rails 6, I add "application.css" on my assets.rb :

Rails.application.config.assets.precompile +=  %w(application.css ie.js pdf.css pdf_shop.css pdf.js sav.css generic.css devise.css /\.(?:svg|eot|woff|ttf|png)$/)

And that's work !

**Comment by sedubois** [comment]
> On Rails 6, with `jsbundling-rails` and `cssbundling-rails`, my manifest.js was this:
> 
> ```
> //= link_tree ../images
> //= link_tree ../builds
> ```
> 
> This was fine until I updated to Rails 7. I'm only getting the error in my CI though (CirlceCI).
> 
> rails 7.0.4.3 sprockets 4.2.0 sprockets-rails-3.4.2

When migrating our app to cssbundling-rails with Dart Sass (for legacy views) and adding Tailwind CSS in parallel with that (for new views), we also encountered the error `Asset X was not declared to be precompiled in production`, and other errors such as `ActionView::Template::Error: Error: Function rgb is missing argument $green` (this came when adding Tailwind CSS).

The solution for us was to add `config.assets.css_compressor = nil` and making sure it is defined as such for all environments, not only production, but also test. See https://github.com/rails/cssbundling-rails/pull/129.

**Comment by dorianmariecom** [comment]
The fix for me was adding the vendor directory to the manifest:

```
//= link_tree ../../../vendor/javascript .js
```
