### ISSUE TITLE
Could you release 3.2.2?

### ISSUE THREAD

**Issue by sanemat** [rails/sprockets-rails#464]
@rafaelfranca could you release latest version? current latest 3.2.1 is released on Sep 1, 2017
we got deprecations with Ruby 2.7

**Comment by ecentell-CPF** [comment]
Any chance a Ruby 2.7 version of the gem getting pushed to rubygems.org soon? I have a client that needs to upgrade to a new version of Ruby and this is holding them up.  There are 34 commits that are made against the project that are not reflected on rubygems.org repo.  Specifically they need the commit c454afd3824a912316ebc8b15e09d64f378a5013 to fix the deprecation.  Please advise if there is an alternative.  Thanks!

**Comment by sanemat** [comment]
you can use this repo directly 😓 
```
gem 'sprockets-rails', github: 'rails/sprockets-rails'
```

**Comment by ecentell-CPF** [comment]
@sanemat thanks for the information guess I should have read more, would you happen to know if I could specify it like this:
gem 'sprockets-rails', github: 'rails/sprockets-rails', ref: 'c454afd3824a912316ebc8b15e09d64f378a5013'
to lock onto that specific commit and everything prior?

**Comment by sanemat** [comment]
https://rubygems.org/gems/sprockets-rails/ 😭

**Comment by sanemat** [comment]
@ecentell-CPF I don't check it, but your format seems ok. https://bundler.io/v2.1/guides/git.html

If you want to use specific ref, I recommend to use `b0b380ef956e66572793dec32c4c67db09664449` or `c269f5e01fdffa5c41350e855183d94ff33d318a`. based on current commit history.

**Comment by pixeltrix** [comment]
@sanemat v3.2.2 has now been released - sorry for the delay.
